export interface Game {
  week: number;
  date: string;
  opponent: string;
  loc: "HOME" | "AWAY";
  venue: string;
}

/* ------------------------------------------------------------------ */
/*  Power-4 Conferences & Rosters (2026)                              */
/* ------------------------------------------------------------------ */

export const CONFERENCES: Record<string, string[]> = {
  ACC: [
    "Boston College", "Cal", "Clemson", "Duke", "Florida State",
    "Georgia Tech", "Louisville", "Miami", "NC State", "North Carolina",
    "Notre Dame", "Pitt", "SMU", "Stanford", "Syracuse", "Virginia",
    "Virginia Tech", "Wake Forest",
  ],
  "Big 12": [
    "Arizona", "Arizona State", "BYU", "Baylor", "Cincinnati",
    "Colorado", "Houston", "Iowa State", "Kansas", "Kansas State",
    "Oklahoma State", "TCU", "Texas Tech", "UCF", "Utah", "West Virginia",
  ],
  "Big Ten": [
    "Illinois", "Indiana", "Iowa", "Maryland", "Michigan",
    "Michigan State", "Minnesota", "Nebraska", "Northwestern",
    "Ohio State", "Oregon", "Penn State", "Purdue", "Rutgers",
    "UCLA", "USC", "Washington", "Wisconsin",
  ],
  SEC: [
    "Alabama", "Arkansas", "Auburn", "Florida", "Georgia",
    "Kentucky", "LSU", "Mississippi State", "Missouri", "Oklahoma",
    "Ole Miss", "South Carolina", "Tennessee", "Texas", "Texas A&M",
    "Vanderbilt",
  ],
};

/* Flat lookup: team → conference */
export const ALL_TEAMS: Record<string, string> = {};
for (const [conf, teams] of Object.entries(CONFERENCES)) {
  for (const t of teams) ALL_TEAMS[t] = conf;
}

export function getTeamConference(team: string): string {
  return ALL_TEAMS[team] || "Unknown";
}

/* ------------------------------------------------------------------ */
/*  2026 Schedules                                                     */
/*  (Projected — real schedules will differ)                           */
/* ------------------------------------------------------------------ */

const SCHEDULES: Record<string, Game[]> = {
  /* ===== BIG TEN ===== */
  Nebraska: [
    { week: 1, date: "SAT SEP 5", opponent: "Ohio", loc: "HOME", venue: "Lincoln, Neb." },
    { week: 2, date: "SAT SEP 12", opponent: "Bowling Green", loc: "HOME", venue: "Lincoln, Neb." },
    { week: 3, date: "SAT SEP 19", opponent: "North Dakota", loc: "HOME", venue: "Lincoln, Neb." },
    { week: 4, date: "SAT SEP 26", opponent: "Michigan State", loc: "AWAY", venue: "East Lansing, Mich." },
    { week: 5, date: "SAT OCT 3", opponent: "Maryland", loc: "HOME", venue: "Lincoln, Neb." },
    { week: 6, date: "SAT OCT 10", opponent: "Indiana", loc: "HOME", venue: "Lincoln, Neb." },
    { week: 7, date: "SAT OCT 17", opponent: "Oregon", loc: "AWAY", venue: "Eugene, Ore." },
    { week: 8, date: "SAT OCT 31", opponent: "Washington", loc: "HOME", venue: "Lincoln, Neb." },
    { week: 9, date: "SAT NOV 7", opponent: "Illinois", loc: "AWAY", venue: "Champaign, Ill." },
    { week: 10, date: "SAT NOV 14", opponent: "Rutgers", loc: "AWAY", venue: "Piscataway, N.J." },
    { week: 11, date: "SAT NOV 21", opponent: "Ohio State", loc: "HOME", venue: "Lincoln, Neb." },
    { week: 12, date: "FRI NOV 27", opponent: "Iowa", loc: "AWAY", venue: "Iowa City, Iowa" },
  ],
  "Ohio State": [
    { week: 1, date: "SAT SEP 5", opponent: "Akron", loc: "HOME", venue: "Columbus, Ohio" },
    { week: 2, date: "SAT SEP 12", opponent: "Texas", loc: "HOME", venue: "Columbus, Ohio" },
    { week: 3, date: "SAT SEP 19", opponent: "Bowling Green", loc: "HOME", venue: "Columbus, Ohio" },
    { week: 4, date: "SAT SEP 26", opponent: "Iowa", loc: "AWAY", venue: "Iowa City, Iowa" },
    { week: 5, date: "SAT OCT 3", opponent: "Purdue", loc: "HOME", venue: "Columbus, Ohio" },
    { week: 6, date: "SAT OCT 10", opponent: "Penn State", loc: "AWAY", venue: "University Park, Pa." },
    { week: 7, date: "SAT OCT 17", opponent: "Wisconsin", loc: "HOME", venue: "Columbus, Ohio" },
    { week: 8, date: "SAT OCT 31", opponent: "Oregon", loc: "AWAY", venue: "Eugene, Ore." },
    { week: 9, date: "SAT NOV 7", opponent: "Northwestern", loc: "HOME", venue: "Columbus, Ohio" },
    { week: 10, date: "SAT NOV 14", opponent: "Maryland", loc: "AWAY", venue: "College Park, Md." },
    { week: 11, date: "SAT NOV 21", opponent: "Nebraska", loc: "AWAY", venue: "Lincoln, Neb." },
    { week: 12, date: "SAT NOV 28", opponent: "Michigan", loc: "HOME", venue: "Columbus, Ohio" },
  ],
  Michigan: [
    { week: 1, date: "SAT SEP 5", opponent: "Fresno State", loc: "HOME", venue: "Ann Arbor, Mich." },
    { week: 2, date: "SAT SEP 12", opponent: "Oklahoma", loc: "AWAY", venue: "Norman, Okla." },
    { week: 3, date: "SAT SEP 19", opponent: "Ball State", loc: "HOME", venue: "Ann Arbor, Mich." },
    { week: 4, date: "SAT SEP 26", opponent: "Wisconsin", loc: "HOME", venue: "Ann Arbor, Mich." },
    { week: 5, date: "SAT OCT 3", opponent: "Rutgers", loc: "AWAY", venue: "Piscataway, N.J." },
    { week: 6, date: "SAT OCT 10", opponent: "USC", loc: "HOME", venue: "Ann Arbor, Mich." },
    { week: 7, date: "SAT OCT 17", opponent: "Illinois", loc: "AWAY", venue: "Champaign, Ill." },
    { week: 8, date: "SAT OCT 31", opponent: "Michigan State", loc: "HOME", venue: "Ann Arbor, Mich." },
    { week: 9, date: "SAT NOV 7", opponent: "Oregon", loc: "AWAY", venue: "Eugene, Ore." },
    { week: 10, date: "SAT NOV 14", opponent: "Northwestern", loc: "HOME", venue: "Ann Arbor, Mich." },
    { week: 11, date: "SAT NOV 21", opponent: "Indiana", loc: "HOME", venue: "Ann Arbor, Mich." },
    { week: 12, date: "SAT NOV 28", opponent: "Ohio State", loc: "AWAY", venue: "Columbus, Ohio" },
  ],
  Oregon: [
    { week: 1, date: "SAT SEP 5", opponent: "Portland State", loc: "HOME", venue: "Eugene, Ore." },
    { week: 2, date: "SAT SEP 12", opponent: "Boise State", loc: "HOME", venue: "Eugene, Ore." },
    { week: 3, date: "SAT SEP 19", opponent: "Georgia", loc: "AWAY", venue: "Athens, Ga." },
    { week: 4, date: "SAT SEP 26", opponent: "UCLA", loc: "HOME", venue: "Eugene, Ore." },
    { week: 5, date: "SAT OCT 3", opponent: "Minnesota", loc: "AWAY", venue: "Minneapolis, Minn." },
    { week: 6, date: "SAT OCT 10", opponent: "Washington", loc: "HOME", venue: "Eugene, Ore." },
    { week: 7, date: "SAT OCT 17", opponent: "Nebraska", loc: "HOME", venue: "Eugene, Ore." },
    { week: 8, date: "SAT OCT 31", opponent: "Ohio State", loc: "HOME", venue: "Eugene, Ore." },
    { week: 9, date: "SAT NOV 7", opponent: "Michigan", loc: "HOME", venue: "Eugene, Ore." },
    { week: 10, date: "SAT NOV 14", opponent: "Penn State", loc: "AWAY", venue: "University Park, Pa." },
    { week: 11, date: "SAT NOV 21", opponent: "USC", loc: "AWAY", venue: "Los Angeles, Calif." },
    { week: 12, date: "SAT NOV 28", opponent: "Washington", loc: "AWAY", venue: "Seattle, Wash." },
  ],
  "Penn State": [
    { week: 1, date: "SAT SEP 5", opponent: "Kent State", loc: "HOME", venue: "University Park, Pa." },
    { week: 2, date: "SAT SEP 12", opponent: "Virginia Tech", loc: "HOME", venue: "University Park, Pa." },
    { week: 3, date: "SAT SEP 19", opponent: "San Jose State", loc: "HOME", venue: "University Park, Pa." },
    { week: 4, date: "SAT SEP 26", opponent: "Northwestern", loc: "AWAY", venue: "Evanston, Ill." },
    { week: 5, date: "SAT OCT 3", opponent: "USC", loc: "HOME", venue: "University Park, Pa." },
    { week: 6, date: "SAT OCT 10", opponent: "Ohio State", loc: "HOME", venue: "University Park, Pa." },
    { week: 7, date: "SAT OCT 17", opponent: "Minnesota", loc: "AWAY", venue: "Minneapolis, Minn." },
    { week: 8, date: "SAT OCT 31", opponent: "Wisconsin", loc: "HOME", venue: "University Park, Pa." },
    { week: 9, date: "SAT NOV 7", opponent: "Iowa", loc: "AWAY", venue: "Iowa City, Iowa" },
    { week: 10, date: "SAT NOV 14", opponent: "Oregon", loc: "HOME", venue: "University Park, Pa." },
    { week: 11, date: "SAT NOV 21", opponent: "Purdue", loc: "HOME", venue: "University Park, Pa." },
    { week: 12, date: "SAT NOV 28", opponent: "Michigan State", loc: "AWAY", venue: "East Lansing, Mich." },
  ],
  USC: [
    { week: 1, date: "SAT SEP 5", opponent: "San Diego State", loc: "HOME", venue: "Los Angeles, Calif." },
    { week: 2, date: "SAT SEP 12", opponent: "LSU", loc: "AWAY", venue: "Baton Rouge, La." },
    { week: 3, date: "SAT SEP 19", opponent: "Nevada", loc: "HOME", venue: "Los Angeles, Calif." },
    { week: 4, date: "SAT SEP 26", opponent: "Rutgers", loc: "HOME", venue: "Los Angeles, Calif." },
    { week: 5, date: "SAT OCT 3", opponent: "Penn State", loc: "AWAY", venue: "University Park, Pa." },
    { week: 6, date: "SAT OCT 10", opponent: "Michigan", loc: "AWAY", venue: "Ann Arbor, Mich." },
    { week: 7, date: "SAT OCT 17", opponent: "Washington", loc: "HOME", venue: "Los Angeles, Calif." },
    { week: 8, date: "SAT OCT 31", opponent: "UCLA", loc: "HOME", venue: "Los Angeles, Calif." },
    { week: 9, date: "SAT NOV 7", opponent: "Minnesota", loc: "AWAY", venue: "Minneapolis, Minn." },
    { week: 10, date: "SAT NOV 14", opponent: "Iowa", loc: "HOME", venue: "Los Angeles, Calif." },
    { week: 11, date: "SAT NOV 21", opponent: "Oregon", loc: "HOME", venue: "Los Angeles, Calif." },
    { week: 12, date: "SAT NOV 28", opponent: "UCLA", loc: "AWAY", venue: "Pasadena, Calif." },
  ],
  Iowa: [
    { week: 1, date: "SAT SEP 5", opponent: "Northern Iowa", loc: "HOME", venue: "Iowa City, Iowa" },
    { week: 2, date: "SAT SEP 12", opponent: "Iowa State", loc: "AWAY", venue: "Ames, Iowa" },
    { week: 3, date: "SAT SEP 19", opponent: "Miami (OH)", loc: "HOME", venue: "Iowa City, Iowa" },
    { week: 4, date: "SAT SEP 26", opponent: "Ohio State", loc: "HOME", venue: "Iowa City, Iowa" },
    { week: 5, date: "SAT OCT 3", opponent: "Illinois", loc: "AWAY", venue: "Champaign, Ill." },
    { week: 6, date: "SAT OCT 10", opponent: "Purdue", loc: "HOME", venue: "Iowa City, Iowa" },
    { week: 7, date: "SAT OCT 17", opponent: "Northwestern", loc: "HOME", venue: "Iowa City, Iowa" },
    { week: 8, date: "SAT OCT 31", opponent: "Minnesota", loc: "AWAY", venue: "Minneapolis, Minn." },
    { week: 9, date: "SAT NOV 7", opponent: "Penn State", loc: "HOME", venue: "Iowa City, Iowa" },
    { week: 10, date: "SAT NOV 14", opponent: "USC", loc: "AWAY", venue: "Los Angeles, Calif." },
    { week: 11, date: "SAT NOV 21", opponent: "Wisconsin", loc: "AWAY", venue: "Madison, Wis." },
    { week: 12, date: "FRI NOV 27", opponent: "Nebraska", loc: "HOME", venue: "Iowa City, Iowa" },
  ],
  Wisconsin: [
    { week: 1, date: "SAT SEP 5", opponent: "Western Michigan", loc: "HOME", venue: "Madison, Wis." },
    { week: 2, date: "SAT SEP 12", opponent: "South Florida", loc: "HOME", venue: "Madison, Wis." },
    { week: 3, date: "SAT SEP 19", opponent: "South Dakota", loc: "HOME", venue: "Madison, Wis." },
    { week: 4, date: "SAT SEP 26", opponent: "Michigan", loc: "AWAY", venue: "Ann Arbor, Mich." },
    { week: 5, date: "SAT OCT 3", opponent: "Purdue", loc: "HOME", venue: "Madison, Wis." },
    { week: 6, date: "SAT OCT 10", opponent: "Indiana", loc: "AWAY", venue: "Bloomington, Ind." },
    { week: 7, date: "SAT OCT 17", opponent: "Ohio State", loc: "AWAY", venue: "Columbus, Ohio" },
    { week: 8, date: "SAT OCT 31", opponent: "Penn State", loc: "AWAY", venue: "University Park, Pa." },
    { week: 9, date: "SAT NOV 7", opponent: "Rutgers", loc: "HOME", venue: "Madison, Wis." },
    { week: 10, date: "SAT NOV 14", opponent: "Minnesota", loc: "HOME", venue: "Madison, Wis." },
    { week: 11, date: "SAT NOV 21", opponent: "Iowa", loc: "HOME", venue: "Madison, Wis." },
    { week: 12, date: "SAT NOV 28", opponent: "Northwestern", loc: "AWAY", venue: "Evanston, Ill." },
  ],
  "Michigan State": [
    { week: 1, date: "SAT SEP 5", opponent: "Central Michigan", loc: "HOME", venue: "East Lansing, Mich." },
    { week: 2, date: "SAT SEP 12", opponent: "Marshall", loc: "HOME", venue: "East Lansing, Mich." },
    { week: 3, date: "SAT SEP 19", opponent: "Western Kentucky", loc: "HOME", venue: "East Lansing, Mich." },
    { week: 4, date: "SAT SEP 26", opponent: "Nebraska", loc: "HOME", venue: "East Lansing, Mich." },
    { week: 5, date: "SAT OCT 3", opponent: "Indiana", loc: "AWAY", venue: "Bloomington, Ind." },
    { week: 6, date: "SAT OCT 10", opponent: "Maryland", loc: "HOME", venue: "East Lansing, Mich." },
    { week: 7, date: "SAT OCT 17", opponent: "Purdue", loc: "AWAY", venue: "West Lafayette, Ind." },
    { week: 8, date: "SAT OCT 31", opponent: "Michigan", loc: "AWAY", venue: "Ann Arbor, Mich." },
    { week: 9, date: "SAT NOV 7", opponent: "UCLA", loc: "HOME", venue: "East Lansing, Mich." },
    { week: 10, date: "SAT NOV 14", opponent: "Illinois", loc: "AWAY", venue: "Champaign, Ill." },
    { week: 11, date: "SAT NOV 21", opponent: "Rutgers", loc: "HOME", venue: "East Lansing, Mich." },
    { week: 12, date: "SAT NOV 28", opponent: "Penn State", loc: "HOME", venue: "East Lansing, Mich." },
  ],
  Indiana: [
    { week: 1, date: "SAT SEP 5", opponent: "FIU", loc: "HOME", venue: "Bloomington, Ind." },
    { week: 2, date: "SAT SEP 12", opponent: "Western Illinois", loc: "HOME", venue: "Bloomington, Ind." },
    { week: 3, date: "SAT SEP 19", opponent: "Louisville", loc: "AWAY", venue: "Louisville, Ky." },
    { week: 4, date: "SAT SEP 26", opponent: "UCLA", loc: "HOME", venue: "Bloomington, Ind." },
    { week: 5, date: "SAT OCT 3", opponent: "Michigan State", loc: "HOME", venue: "Bloomington, Ind." },
    { week: 6, date: "SAT OCT 10", opponent: "Nebraska", loc: "AWAY", venue: "Lincoln, Neb." },
    { week: 7, date: "SAT OCT 17", opponent: "Maryland", loc: "HOME", venue: "Bloomington, Ind." },
    { week: 8, date: "SAT OCT 31", opponent: "Purdue", loc: "AWAY", venue: "West Lafayette, Ind." },
    { week: 9, date: "SAT NOV 7", opponent: "Washington", loc: "HOME", venue: "Bloomington, Ind." },
    { week: 10, date: "SAT NOV 14", opponent: "USC", loc: "AWAY", venue: "Los Angeles, Calif." },
    { week: 11, date: "SAT NOV 21", opponent: "Michigan", loc: "AWAY", venue: "Ann Arbor, Mich." },
    { week: 12, date: "SAT NOV 28", opponent: "Purdue", loc: "HOME", venue: "Bloomington, Ind." },
  ],
  Minnesota: [
    { week: 1, date: "SAT SEP 5", opponent: "North Dakota State", loc: "HOME", venue: "Minneapolis, Minn." },
    { week: 2, date: "SAT SEP 12", opponent: "Eastern Michigan", loc: "HOME", venue: "Minneapolis, Minn." },
    { week: 3, date: "SAT SEP 19", opponent: "Colorado", loc: "AWAY", venue: "Boulder, Colo." },
    { week: 4, date: "SAT SEP 26", opponent: "Illinois", loc: "HOME", venue: "Minneapolis, Minn." },
    { week: 5, date: "SAT OCT 3", opponent: "Oregon", loc: "HOME", venue: "Minneapolis, Minn." },
    { week: 6, date: "SAT OCT 10", opponent: "UCLA", loc: "AWAY", venue: "Pasadena, Calif." },
    { week: 7, date: "SAT OCT 17", opponent: "Penn State", loc: "HOME", venue: "Minneapolis, Minn." },
    { week: 8, date: "SAT OCT 31", opponent: "Iowa", loc: "HOME", venue: "Minneapolis, Minn." },
    { week: 9, date: "SAT NOV 7", opponent: "USC", loc: "HOME", venue: "Minneapolis, Minn." },
    { week: 10, date: "SAT NOV 14", opponent: "Wisconsin", loc: "AWAY", venue: "Madison, Wis." },
    { week: 11, date: "SAT NOV 21", opponent: "Purdue", loc: "AWAY", venue: "West Lafayette, Ind." },
    { week: 12, date: "SAT NOV 28", opponent: "Maryland", loc: "HOME", venue: "Minneapolis, Minn." },
  ],
  Illinois: [
    { week: 1, date: "SAT SEP 5", opponent: "Eastern Illinois", loc: "HOME", venue: "Champaign, Ill." },
    { week: 2, date: "SAT SEP 12", opponent: "South Carolina", loc: "AWAY", venue: "Columbia, S.C." },
    { week: 3, date: "SAT SEP 19", opponent: "Akron", loc: "HOME", venue: "Champaign, Ill." },
    { week: 4, date: "SAT SEP 26", opponent: "Minnesota", loc: "AWAY", venue: "Minneapolis, Minn." },
    { week: 5, date: "SAT OCT 3", opponent: "Iowa", loc: "HOME", venue: "Champaign, Ill." },
    { week: 6, date: "SAT OCT 10", opponent: "Rutgers", loc: "AWAY", venue: "Piscataway, N.J." },
    { week: 7, date: "SAT OCT 17", opponent: "Michigan", loc: "HOME", venue: "Champaign, Ill." },
    { week: 8, date: "SAT OCT 31", opponent: "Northwestern", loc: "AWAY", venue: "Evanston, Ill." },
    { week: 9, date: "SAT NOV 7", opponent: "Nebraska", loc: "HOME", venue: "Champaign, Ill." },
    { week: 10, date: "SAT NOV 14", opponent: "Michigan State", loc: "HOME", venue: "Champaign, Ill." },
    { week: 11, date: "SAT NOV 21", opponent: "Washington", loc: "AWAY", venue: "Seattle, Wash." },
    { week: 12, date: "SAT NOV 28", opponent: "Northwestern", loc: "HOME", venue: "Champaign, Ill." },
  ],
  Maryland: [
    { week: 1, date: "SAT SEP 5", opponent: "Towson", loc: "HOME", venue: "College Park, Md." },
    { week: 2, date: "SAT SEP 12", opponent: "Charlotte", loc: "HOME", venue: "College Park, Md." },
    { week: 3, date: "SAT SEP 19", opponent: "Virginia", loc: "AWAY", venue: "Charlottesville, Va." },
    { week: 4, date: "SAT SEP 26", opponent: "Washington", loc: "HOME", venue: "College Park, Md." },
    { week: 5, date: "SAT OCT 3", opponent: "Nebraska", loc: "AWAY", venue: "Lincoln, Neb." },
    { week: 6, date: "SAT OCT 10", opponent: "Michigan State", loc: "AWAY", venue: "East Lansing, Mich." },
    { week: 7, date: "SAT OCT 17", opponent: "Indiana", loc: "AWAY", venue: "Bloomington, Ind." },
    { week: 8, date: "SAT OCT 31", opponent: "Rutgers", loc: "HOME", venue: "College Park, Md." },
    { week: 9, date: "SAT NOV 7", opponent: "UCLA", loc: "HOME", venue: "College Park, Md." },
    { week: 10, date: "SAT NOV 14", opponent: "Ohio State", loc: "HOME", venue: "College Park, Md." },
    { week: 11, date: "SAT NOV 21", opponent: "Northwestern", loc: "AWAY", venue: "Evanston, Ill." },
    { week: 12, date: "SAT NOV 28", opponent: "Minnesota", loc: "AWAY", venue: "Minneapolis, Minn." },
  ],
  Purdue: [
    { week: 1, date: "SAT SEP 5", opponent: "Indiana State", loc: "HOME", venue: "West Lafayette, Ind." },
    { week: 2, date: "SAT SEP 12", opponent: "Marshall", loc: "HOME", venue: "West Lafayette, Ind." },
    { week: 3, date: "SAT SEP 19", opponent: "Notre Dame", loc: "AWAY", venue: "South Bend, Ind." },
    { week: 4, date: "SAT SEP 26", opponent: "Rutgers", loc: "HOME", venue: "West Lafayette, Ind." },
    { week: 5, date: "SAT OCT 3", opponent: "Wisconsin", loc: "AWAY", venue: "Madison, Wis." },
    { week: 6, date: "SAT OCT 10", opponent: "Iowa", loc: "AWAY", venue: "Iowa City, Iowa" },
    { week: 7, date: "SAT OCT 17", opponent: "Michigan State", loc: "HOME", venue: "West Lafayette, Ind." },
    { week: 8, date: "SAT OCT 31", opponent: "Indiana", loc: "HOME", venue: "West Lafayette, Ind." },
    { week: 9, date: "SAT NOV 7", opponent: "Northwestern", loc: "AWAY", venue: "Evanston, Ill." },
    { week: 10, date: "SAT NOV 14", opponent: "UCLA", loc: "HOME", venue: "West Lafayette, Ind." },
    { week: 11, date: "SAT NOV 21", opponent: "Minnesota", loc: "HOME", venue: "West Lafayette, Ind." },
    { week: 12, date: "SAT NOV 28", opponent: "Indiana", loc: "AWAY", venue: "Bloomington, Ind." },
  ],
  Rutgers: [
    { week: 1, date: "SAT SEP 5", opponent: "Howard", loc: "HOME", venue: "Piscataway, N.J." },
    { week: 2, date: "SAT SEP 12", opponent: "Temple", loc: "HOME", venue: "Piscataway, N.J." },
    { week: 3, date: "SAT SEP 19", opponent: "Army", loc: "AWAY", venue: "West Point, N.Y." },
    { week: 4, date: "SAT SEP 26", opponent: "Purdue", loc: "AWAY", venue: "West Lafayette, Ind." },
    { week: 5, date: "SAT OCT 3", opponent: "Michigan", loc: "HOME", venue: "Piscataway, N.J." },
    { week: 6, date: "SAT OCT 10", opponent: "Illinois", loc: "HOME", venue: "Piscataway, N.J." },
    { week: 7, date: "SAT OCT 17", opponent: "USC", loc: "AWAY", venue: "Los Angeles, Calif." },
    { week: 8, date: "SAT OCT 31", opponent: "Maryland", loc: "AWAY", venue: "College Park, Md." },
    { week: 9, date: "SAT NOV 7", opponent: "Wisconsin", loc: "AWAY", venue: "Madison, Wis." },
    { week: 10, date: "SAT NOV 14", opponent: "Nebraska", loc: "HOME", venue: "Piscataway, N.J." },
    { week: 11, date: "SAT NOV 21", opponent: "Michigan State", loc: "AWAY", venue: "East Lansing, Mich." },
    { week: 12, date: "SAT NOV 28", opponent: "Washington", loc: "HOME", venue: "Piscataway, N.J." },
  ],
  Northwestern: [
    { week: 1, date: "SAT SEP 5", opponent: "Eastern Michigan", loc: "HOME", venue: "Evanston, Ill." },
    { week: 2, date: "SAT SEP 12", opponent: "Duke", loc: "HOME", venue: "Evanston, Ill." },
    { week: 3, date: "SAT SEP 19", opponent: "UConn", loc: "HOME", venue: "Evanston, Ill." },
    { week: 4, date: "SAT SEP 26", opponent: "Penn State", loc: "HOME", venue: "Evanston, Ill." },
    { week: 5, date: "SAT OCT 3", opponent: "Washington", loc: "AWAY", venue: "Seattle, Wash." },
    { week: 6, date: "SAT OCT 10", opponent: "Oregon", loc: "HOME", venue: "Evanston, Ill." },
    { week: 7, date: "SAT OCT 17", opponent: "Iowa", loc: "AWAY", venue: "Iowa City, Iowa" },
    { week: 8, date: "SAT OCT 31", opponent: "Illinois", loc: "HOME", venue: "Evanston, Ill." },
    { week: 9, date: "SAT NOV 7", opponent: "Purdue", loc: "HOME", venue: "Evanston, Ill." },
    { week: 10, date: "SAT NOV 14", opponent: "Michigan", loc: "AWAY", venue: "Ann Arbor, Mich." },
    { week: 11, date: "SAT NOV 21", opponent: "Maryland", loc: "HOME", venue: "Evanston, Ill." },
    { week: 12, date: "SAT NOV 28", opponent: "Wisconsin", loc: "HOME", venue: "Evanston, Ill." },
  ],
  UCLA: [
    { week: 1, date: "SAT SEP 5", opponent: "Hawaii", loc: "HOME", venue: "Pasadena, Calif." },
    { week: 2, date: "SAT SEP 12", opponent: "UNLV", loc: "HOME", venue: "Pasadena, Calif." },
    { week: 3, date: "SAT SEP 19", opponent: "Clemson", loc: "AWAY", venue: "Clemson, S.C." },
    { week: 4, date: "SAT SEP 26", opponent: "Oregon", loc: "AWAY", venue: "Eugene, Ore." },
    { week: 5, date: "SAT OCT 3", opponent: "Washington", loc: "HOME", venue: "Pasadena, Calif." },
    { week: 6, date: "SAT OCT 10", opponent: "Minnesota", loc: "HOME", venue: "Pasadena, Calif." },
    { week: 7, date: "SAT OCT 17", opponent: "Iowa", loc: "AWAY", venue: "Iowa City, Iowa" },
    { week: 8, date: "SAT OCT 31", opponent: "USC", loc: "AWAY", venue: "Los Angeles, Calif." },
    { week: 9, date: "SAT NOV 7", opponent: "Michigan State", loc: "AWAY", venue: "East Lansing, Mich." },
    { week: 10, date: "SAT NOV 14", opponent: "Purdue", loc: "AWAY", venue: "West Lafayette, Ind." },
    { week: 11, date: "SAT NOV 21", opponent: "Washington", loc: "HOME", venue: "Pasadena, Calif." },
    { week: 12, date: "SAT NOV 28", opponent: "USC", loc: "HOME", venue: "Pasadena, Calif." },
  ],
  Washington: [
    { week: 1, date: "SAT SEP 5", opponent: "Weber State", loc: "HOME", venue: "Seattle, Wash." },
    { week: 2, date: "SAT SEP 12", opponent: "Arizona", loc: "HOME", venue: "Seattle, Wash." },
    { week: 3, date: "SAT SEP 19", opponent: "Montana", loc: "HOME", venue: "Seattle, Wash." },
    { week: 4, date: "SAT SEP 26", opponent: "Maryland", loc: "AWAY", venue: "College Park, Md." },
    { week: 5, date: "SAT OCT 3", opponent: "Northwestern", loc: "HOME", venue: "Seattle, Wash." },
    { week: 6, date: "SAT OCT 10", opponent: "Oregon", loc: "AWAY", venue: "Eugene, Ore." },
    { week: 7, date: "SAT OCT 17", opponent: "USC", loc: "AWAY", venue: "Los Angeles, Calif." },
    { week: 8, date: "SAT OCT 31", opponent: "Nebraska", loc: "AWAY", venue: "Lincoln, Neb." },
    { week: 9, date: "SAT NOV 7", opponent: "Indiana", loc: "AWAY", venue: "Bloomington, Ind." },
    { week: 10, date: "SAT NOV 14", opponent: "Oregon", loc: "HOME", venue: "Seattle, Wash." },
    { week: 11, date: "SAT NOV 21", opponent: "UCLA", loc: "AWAY", venue: "Pasadena, Calif." },
    { week: 12, date: "SAT NOV 28", opponent: "Rutgers", loc: "AWAY", venue: "Piscataway, N.J." },
  ],

  /* ===== SEC ===== */
  Alabama: [
    { week: 1, date: "SAT SEP 5", opponent: "Florida State", loc: "HOME", venue: "Tuscaloosa, Ala." },
    { week: 2, date: "SAT SEP 12", opponent: "South Florida", loc: "HOME", venue: "Tuscaloosa, Ala." },
    { week: 3, date: "SAT SEP 19", opponent: "Mercer", loc: "HOME", venue: "Tuscaloosa, Ala." },
    { week: 4, date: "SAT SEP 26", opponent: "Vanderbilt", loc: "AWAY", venue: "Nashville, Tenn." },
    { week: 5, date: "SAT OCT 3", opponent: "Ole Miss", loc: "HOME", venue: "Tuscaloosa, Ala." },
    { week: 6, date: "SAT OCT 10", opponent: "Texas", loc: "AWAY", venue: "Austin, Texas" },
    { week: 7, date: "SAT OCT 17", opponent: "Tennessee", loc: "HOME", venue: "Tuscaloosa, Ala." },
    { week: 8, date: "SAT OCT 31", opponent: "Missouri", loc: "AWAY", venue: "Columbia, Mo." },
    { week: 9, date: "SAT NOV 7", opponent: "LSU", loc: "HOME", venue: "Tuscaloosa, Ala." },
    { week: 10, date: "SAT NOV 14", opponent: "Oklahoma", loc: "AWAY", venue: "Norman, Okla." },
    { week: 11, date: "SAT NOV 21", opponent: "Georgia", loc: "HOME", venue: "Tuscaloosa, Ala." },
    { week: 12, date: "SAT NOV 28", opponent: "Auburn", loc: "AWAY", venue: "Auburn, Ala." },
  ],
  Georgia: [
    { week: 1, date: "SAT SEP 5", opponent: "Tennessee Tech", loc: "HOME", venue: "Athens, Ga." },
    { week: 2, date: "SAT SEP 12", opponent: "Clemson", loc: "HOME", venue: "Athens, Ga." },
    { week: 3, date: "SAT SEP 19", opponent: "Oregon", loc: "HOME", venue: "Athens, Ga." },
    { week: 4, date: "SAT SEP 26", opponent: "Mississippi State", loc: "AWAY", venue: "Starkville, Miss." },
    { week: 5, date: "SAT OCT 3", opponent: "Auburn", loc: "HOME", venue: "Athens, Ga." },
    { week: 6, date: "SAT OCT 10", opponent: "Vanderbilt", loc: "HOME", venue: "Athens, Ga." },
    { week: 7, date: "SAT OCT 17", opponent: "Texas", loc: "AWAY", venue: "Austin, Texas" },
    { week: 8, date: "SAT OCT 31", opponent: "Florida", loc: "AWAY", venue: "Jacksonville, Fla." },
    { week: 9, date: "SAT NOV 7", opponent: "Missouri", loc: "HOME", venue: "Athens, Ga." },
    { week: 10, date: "SAT NOV 14", opponent: "Tennessee", loc: "AWAY", venue: "Knoxville, Tenn." },
    { week: 11, date: "SAT NOV 21", opponent: "Alabama", loc: "AWAY", venue: "Tuscaloosa, Ala." },
    { week: 12, date: "SAT NOV 28", opponent: "Georgia Tech", loc: "HOME", venue: "Athens, Ga." },
  ],
  Texas: [
    { week: 1, date: "SAT SEP 5", opponent: "UTSA", loc: "HOME", venue: "Austin, Texas" },
    { week: 2, date: "SAT SEP 12", opponent: "Ohio State", loc: "AWAY", venue: "Columbus, Ohio" },
    { week: 3, date: "SAT SEP 19", opponent: "UTEP", loc: "HOME", venue: "Austin, Texas" },
    { week: 4, date: "SAT SEP 26", opponent: "Mississippi State", loc: "HOME", venue: "Austin, Texas" },
    { week: 5, date: "SAT OCT 3", opponent: "Oklahoma", loc: "HOME", venue: "Dallas, Texas" },
    { week: 6, date: "SAT OCT 10", opponent: "Alabama", loc: "HOME", venue: "Austin, Texas" },
    { week: 7, date: "SAT OCT 17", opponent: "Georgia", loc: "HOME", venue: "Austin, Texas" },
    { week: 8, date: "SAT OCT 31", opponent: "Vanderbilt", loc: "AWAY", venue: "Nashville, Tenn." },
    { week: 9, date: "SAT NOV 7", opponent: "Florida", loc: "AWAY", venue: "Gainesville, Fla." },
    { week: 10, date: "SAT NOV 14", opponent: "Arkansas", loc: "HOME", venue: "Austin, Texas" },
    { week: 11, date: "SAT NOV 21", opponent: "Kentucky", loc: "AWAY", venue: "Lexington, Ky." },
    { week: 12, date: "SAT NOV 28", opponent: "Texas A&M", loc: "HOME", venue: "Austin, Texas" },
  ],
  "Texas A&M": [
    { week: 1, date: "SAT SEP 5", opponent: "Lamar", loc: "HOME", venue: "College Station, Texas" },
    { week: 2, date: "SAT SEP 12", opponent: "Baylor", loc: "HOME", venue: "College Station, Texas" },
    { week: 3, date: "SAT SEP 19", opponent: "Tulane", loc: "HOME", venue: "College Station, Texas" },
    { week: 4, date: "SAT SEP 26", opponent: "Arkansas", loc: "AWAY", venue: "Fayetteville, Ark." },
    { week: 5, date: "SAT OCT 3", opponent: "Missouri", loc: "HOME", venue: "College Station, Texas" },
    { week: 6, date: "SAT OCT 10", opponent: "South Carolina", loc: "AWAY", venue: "Columbia, S.C." },
    { week: 7, date: "SAT OCT 17", opponent: "LSU", loc: "HOME", venue: "College Station, Texas" },
    { week: 8, date: "SAT OCT 31", opponent: "Ole Miss", loc: "AWAY", venue: "Oxford, Miss." },
    { week: 9, date: "SAT NOV 7", opponent: "Auburn", loc: "HOME", venue: "College Station, Texas" },
    { week: 10, date: "SAT NOV 14", opponent: "Florida", loc: "HOME", venue: "College Station, Texas" },
    { week: 11, date: "SAT NOV 21", opponent: "Tennessee", loc: "AWAY", venue: "Knoxville, Tenn." },
    { week: 12, date: "SAT NOV 28", opponent: "Texas", loc: "AWAY", venue: "Austin, Texas" },
  ],
  Tennessee: [
    { week: 1, date: "SAT SEP 5", opponent: "Chattanooga", loc: "HOME", venue: "Knoxville, Tenn." },
    { week: 2, date: "SAT SEP 12", opponent: "NC State", loc: "HOME", venue: "Knoxville, Tenn." },
    { week: 3, date: "SAT SEP 19", opponent: "Kent State", loc: "HOME", venue: "Knoxville, Tenn." },
    { week: 4, date: "SAT SEP 26", opponent: "Florida", loc: "HOME", venue: "Knoxville, Tenn." },
    { week: 5, date: "SAT OCT 3", opponent: "Arkansas", loc: "AWAY", venue: "Fayetteville, Ark." },
    { week: 6, date: "SAT OCT 10", opponent: "Mississippi State", loc: "HOME", venue: "Knoxville, Tenn." },
    { week: 7, date: "SAT OCT 17", opponent: "Alabama", loc: "AWAY", venue: "Tuscaloosa, Ala." },
    { week: 8, date: "SAT OCT 31", opponent: "Kentucky", loc: "HOME", venue: "Knoxville, Tenn." },
    { week: 9, date: "SAT NOV 7", opponent: "South Carolina", loc: "AWAY", venue: "Columbia, S.C." },
    { week: 10, date: "SAT NOV 14", opponent: "Georgia", loc: "HOME", venue: "Knoxville, Tenn." },
    { week: 11, date: "SAT NOV 21", opponent: "Texas A&M", loc: "HOME", venue: "Knoxville, Tenn." },
    { week: 12, date: "SAT NOV 28", opponent: "Vanderbilt", loc: "AWAY", venue: "Nashville, Tenn." },
  ],
  LSU: [
    { week: 1, date: "SAT SEP 5", opponent: "Grambling", loc: "HOME", venue: "Baton Rouge, La." },
    { week: 2, date: "SAT SEP 12", opponent: "USC", loc: "HOME", venue: "Baton Rouge, La." },
    { week: 3, date: "SAT SEP 19", opponent: "Rice", loc: "HOME", venue: "Baton Rouge, La." },
    { week: 4, date: "SAT SEP 26", opponent: "South Carolina", loc: "AWAY", venue: "Columbia, S.C." },
    { week: 5, date: "SAT OCT 3", opponent: "Kentucky", loc: "HOME", venue: "Baton Rouge, La." },
    { week: 6, date: "SAT OCT 10", opponent: "Ole Miss", loc: "AWAY", venue: "Oxford, Miss." },
    { week: 7, date: "SAT OCT 17", opponent: "Texas A&M", loc: "AWAY", venue: "College Station, Texas" },
    { week: 8, date: "SAT OCT 31", opponent: "Arkansas", loc: "HOME", venue: "Baton Rouge, La." },
    { week: 9, date: "SAT NOV 7", opponent: "Alabama", loc: "AWAY", venue: "Tuscaloosa, Ala." },
    { week: 10, date: "SAT NOV 14", opponent: "Vanderbilt", loc: "HOME", venue: "Baton Rouge, La." },
    { week: 11, date: "SAT NOV 21", opponent: "Oklahoma", loc: "HOME", venue: "Baton Rouge, La." },
    { week: 12, date: "SAT NOV 28", opponent: "Florida", loc: "HOME", venue: "Baton Rouge, La." },
  ],
  "Ole Miss": [
    { week: 1, date: "SAT SEP 5", opponent: "UT Martin", loc: "HOME", venue: "Oxford, Miss." },
    { week: 2, date: "SAT SEP 12", opponent: "Wake Forest", loc: "HOME", venue: "Oxford, Miss." },
    { week: 3, date: "SAT SEP 19", opponent: "Middle Tennessee", loc: "HOME", venue: "Oxford, Miss." },
    { week: 4, date: "SAT SEP 26", opponent: "Kentucky", loc: "AWAY", venue: "Lexington, Ky." },
    { week: 5, date: "SAT OCT 3", opponent: "Alabama", loc: "AWAY", venue: "Tuscaloosa, Ala." },
    { week: 6, date: "SAT OCT 10", opponent: "LSU", loc: "HOME", venue: "Oxford, Miss." },
    { week: 7, date: "SAT OCT 17", opponent: "Arkansas", loc: "HOME", venue: "Oxford, Miss." },
    { week: 8, date: "SAT OCT 31", opponent: "Texas A&M", loc: "HOME", venue: "Oxford, Miss." },
    { week: 9, date: "SAT NOV 7", opponent: "Oklahoma", loc: "AWAY", venue: "Norman, Okla." },
    { week: 10, date: "SAT NOV 14", opponent: "Florida", loc: "HOME", venue: "Oxford, Miss." },
    { week: 11, date: "SAT NOV 21", opponent: "Vanderbilt", loc: "AWAY", venue: "Nashville, Tenn." },
    { week: 12, date: "SAT NOV 28", opponent: "Mississippi State", loc: "HOME", venue: "Oxford, Miss." },
  ],
  Oklahoma: [
    { week: 1, date: "SAT SEP 5", opponent: "Temple", loc: "HOME", venue: "Norman, Okla." },
    { week: 2, date: "SAT SEP 12", opponent: "Michigan", loc: "HOME", venue: "Norman, Okla." },
    { week: 3, date: "SAT SEP 19", opponent: "Tulsa", loc: "HOME", venue: "Norman, Okla." },
    { week: 4, date: "SAT SEP 26", opponent: "Auburn", loc: "AWAY", venue: "Auburn, Ala." },
    { week: 5, date: "SAT OCT 3", opponent: "Texas", loc: "AWAY", venue: "Dallas, Texas" },
    { week: 6, date: "SAT OCT 10", opponent: "Missouri", loc: "HOME", venue: "Norman, Okla." },
    { week: 7, date: "SAT OCT 17", opponent: "South Carolina", loc: "AWAY", venue: "Columbia, S.C." },
    { week: 8, date: "SAT OCT 31", opponent: "Florida", loc: "HOME", venue: "Norman, Okla." },
    { week: 9, date: "SAT NOV 7", opponent: "Ole Miss", loc: "HOME", venue: "Norman, Okla." },
    { week: 10, date: "SAT NOV 14", opponent: "Alabama", loc: "HOME", venue: "Norman, Okla." },
    { week: 11, date: "SAT NOV 21", opponent: "LSU", loc: "AWAY", venue: "Baton Rouge, La." },
    { week: 12, date: "SAT NOV 28", opponent: "Oklahoma State", loc: "HOME", venue: "Norman, Okla." },
  ],
  Florida: [
    { week: 1, date: "SAT SEP 5", opponent: "Eastern Washington", loc: "HOME", venue: "Gainesville, Fla." },
    { week: 2, date: "SAT SEP 12", opponent: "Miami", loc: "AWAY", venue: "Miami Gardens, Fla." },
    { week: 3, date: "SAT SEP 19", opponent: "USF", loc: "HOME", venue: "Gainesville, Fla." },
    { week: 4, date: "SAT SEP 26", opponent: "Tennessee", loc: "AWAY", venue: "Knoxville, Tenn." },
    { week: 5, date: "SAT OCT 3", opponent: "Mississippi State", loc: "HOME", venue: "Gainesville, Fla." },
    { week: 6, date: "SAT OCT 10", opponent: "Kentucky", loc: "AWAY", venue: "Lexington, Ky." },
    { week: 7, date: "SAT OCT 17", opponent: "Vanderbilt", loc: "HOME", venue: "Gainesville, Fla." },
    { week: 8, date: "SAT OCT 31", opponent: "Georgia", loc: "HOME", venue: "Jacksonville, Fla." },
    { week: 9, date: "SAT NOV 7", opponent: "Texas", loc: "HOME", venue: "Gainesville, Fla." },
    { week: 10, date: "SAT NOV 14", opponent: "Ole Miss", loc: "AWAY", venue: "Oxford, Miss." },
    { week: 11, date: "SAT NOV 21", opponent: "South Carolina", loc: "HOME", venue: "Gainesville, Fla." },
    { week: 12, date: "SAT NOV 28", opponent: "LSU", loc: "AWAY", venue: "Baton Rouge, La." },
  ],
  Auburn: [
    { week: 1, date: "SAT SEP 5", opponent: "Alabama A&M", loc: "HOME", venue: "Auburn, Ala." },
    { week: 2, date: "SAT SEP 12", opponent: "California", loc: "HOME", venue: "Auburn, Ala." },
    { week: 3, date: "SAT SEP 19", opponent: "New Mexico", loc: "HOME", venue: "Auburn, Ala." },
    { week: 4, date: "SAT SEP 26", opponent: "Oklahoma", loc: "HOME", venue: "Auburn, Ala." },
    { week: 5, date: "SAT OCT 3", opponent: "Georgia", loc: "AWAY", venue: "Athens, Ga." },
    { week: 6, date: "SAT OCT 10", opponent: "Arkansas", loc: "HOME", venue: "Auburn, Ala." },
    { week: 7, date: "SAT OCT 17", opponent: "Missouri", loc: "AWAY", venue: "Columbia, Mo." },
    { week: 8, date: "SAT OCT 31", opponent: "Mississippi State", loc: "HOME", venue: "Auburn, Ala." },
    { week: 9, date: "SAT NOV 7", opponent: "Texas A&M", loc: "AWAY", venue: "College Station, Texas" },
    { week: 10, date: "SAT NOV 14", opponent: "Kentucky", loc: "HOME", venue: "Auburn, Ala." },
    { week: 11, date: "SAT NOV 21", opponent: "South Carolina", loc: "AWAY", venue: "Columbia, S.C." },
    { week: 12, date: "SAT NOV 28", opponent: "Alabama", loc: "HOME", venue: "Auburn, Ala." },
  ],
  Missouri: [
    { week: 1, date: "SAT SEP 5", opponent: "Central Arkansas", loc: "HOME", venue: "Columbia, Mo." },
    { week: 2, date: "SAT SEP 12", opponent: "Buffalo", loc: "HOME", venue: "Columbia, Mo." },
    { week: 3, date: "SAT SEP 19", opponent: "Boston College", loc: "AWAY", venue: "Chestnut Hill, Mass." },
    { week: 4, date: "SAT SEP 26", opponent: "Vanderbilt", loc: "HOME", venue: "Columbia, Mo." },
    { week: 5, date: "SAT OCT 3", opponent: "Texas A&M", loc: "AWAY", venue: "College Station, Texas" },
    { week: 6, date: "SAT OCT 10", opponent: "Oklahoma", loc: "AWAY", venue: "Norman, Okla." },
    { week: 7, date: "SAT OCT 17", opponent: "Auburn", loc: "HOME", venue: "Columbia, Mo." },
    { week: 8, date: "SAT OCT 31", opponent: "Alabama", loc: "HOME", venue: "Columbia, Mo." },
    { week: 9, date: "SAT NOV 7", opponent: "Georgia", loc: "AWAY", venue: "Athens, Ga." },
    { week: 10, date: "SAT NOV 14", opponent: "Mississippi State", loc: "HOME", venue: "Columbia, Mo." },
    { week: 11, date: "SAT NOV 21", opponent: "Arkansas", loc: "HOME", venue: "Columbia, Mo." },
    { week: 12, date: "SAT NOV 28", opponent: "Kansas", loc: "AWAY", venue: "Lawrence, Kan." },
  ],
  Arkansas: [
    { week: 1, date: "SAT SEP 5", opponent: "Arkansas Pine Bluff", loc: "HOME", venue: "Fayetteville, Ark." },
    { week: 2, date: "SAT SEP 12", opponent: "Oklahoma State", loc: "HOME", venue: "Fayetteville, Ark." },
    { week: 3, date: "SAT SEP 19", opponent: "UTSA", loc: "HOME", venue: "Fayetteville, Ark." },
    { week: 4, date: "SAT SEP 26", opponent: "Texas A&M", loc: "HOME", venue: "Fayetteville, Ark." },
    { week: 5, date: "SAT OCT 3", opponent: "Tennessee", loc: "HOME", venue: "Fayetteville, Ark." },
    { week: 6, date: "SAT OCT 10", opponent: "Auburn", loc: "AWAY", venue: "Auburn, Ala." },
    { week: 7, date: "SAT OCT 17", opponent: "Ole Miss", loc: "AWAY", venue: "Oxford, Miss." },
    { week: 8, date: "SAT OCT 31", opponent: "LSU", loc: "AWAY", venue: "Baton Rouge, La." },
    { week: 9, date: "SAT NOV 7", opponent: "Kentucky", loc: "HOME", venue: "Fayetteville, Ark." },
    { week: 10, date: "SAT NOV 14", opponent: "Texas", loc: "AWAY", venue: "Austin, Texas" },
    { week: 11, date: "SAT NOV 21", opponent: "Missouri", loc: "AWAY", venue: "Columbia, Mo." },
    { week: 12, date: "SAT NOV 28", opponent: "Mississippi State", loc: "HOME", venue: "Fayetteville, Ark." },
  ],
  Kentucky: [
    { week: 1, date: "SAT SEP 5", opponent: "Murray State", loc: "HOME", venue: "Lexington, Ky." },
    { week: 2, date: "SAT SEP 12", opponent: "Louisville", loc: "AWAY", venue: "Louisville, Ky." },
    { week: 3, date: "SAT SEP 19", opponent: "Ohio", loc: "HOME", venue: "Lexington, Ky." },
    { week: 4, date: "SAT SEP 26", opponent: "Ole Miss", loc: "HOME", venue: "Lexington, Ky." },
    { week: 5, date: "SAT OCT 3", opponent: "LSU", loc: "AWAY", venue: "Baton Rouge, La." },
    { week: 6, date: "SAT OCT 10", opponent: "Florida", loc: "HOME", venue: "Lexington, Ky." },
    { week: 7, date: "SAT OCT 17", opponent: "Mississippi State", loc: "AWAY", venue: "Starkville, Miss." },
    { week: 8, date: "SAT OCT 31", opponent: "Tennessee", loc: "AWAY", venue: "Knoxville, Tenn." },
    { week: 9, date: "SAT NOV 7", opponent: "Arkansas", loc: "AWAY", venue: "Fayetteville, Ark." },
    { week: 10, date: "SAT NOV 14", opponent: "Auburn", loc: "AWAY", venue: "Auburn, Ala." },
    { week: 11, date: "SAT NOV 21", opponent: "Texas", loc: "HOME", venue: "Lexington, Ky." },
    { week: 12, date: "SAT NOV 28", opponent: "Vanderbilt", loc: "HOME", venue: "Lexington, Ky." },
  ],
  "South Carolina": [
    { week: 1, date: "SAT SEP 5", opponent: "The Citadel", loc: "HOME", venue: "Columbia, S.C." },
    { week: 2, date: "SAT SEP 12", opponent: "Illinois", loc: "HOME", venue: "Columbia, S.C." },
    { week: 3, date: "SAT SEP 19", opponent: "Appalachian State", loc: "HOME", venue: "Columbia, S.C." },
    { week: 4, date: "SAT SEP 26", opponent: "LSU", loc: "HOME", venue: "Columbia, S.C." },
    { week: 5, date: "SAT OCT 3", opponent: "Vanderbilt", loc: "AWAY", venue: "Nashville, Tenn." },
    { week: 6, date: "SAT OCT 10", opponent: "Texas A&M", loc: "HOME", venue: "Columbia, S.C." },
    { week: 7, date: "SAT OCT 17", opponent: "Oklahoma", loc: "HOME", venue: "Columbia, S.C." },
    { week: 8, date: "SAT OCT 31", opponent: "Mississippi State", loc: "AWAY", venue: "Starkville, Miss." },
    { week: 9, date: "SAT NOV 7", opponent: "Tennessee", loc: "HOME", venue: "Columbia, S.C." },
    { week: 10, date: "SAT NOV 14", opponent: "Missouri", loc: "AWAY", venue: "Columbia, Mo." },
    { week: 11, date: "SAT NOV 21", opponent: "Auburn", loc: "HOME", venue: "Columbia, S.C." },
    { week: 12, date: "SAT NOV 28", opponent: "Clemson", loc: "AWAY", venue: "Clemson, S.C." },
  ],
  "Mississippi State": [
    { week: 1, date: "SAT SEP 5", opponent: "Jackson State", loc: "HOME", venue: "Starkville, Miss." },
    { week: 2, date: "SAT SEP 12", opponent: "Tulane", loc: "HOME", venue: "Starkville, Miss." },
    { week: 3, date: "SAT SEP 19", opponent: "Southern Miss", loc: "HOME", venue: "Starkville, Miss." },
    { week: 4, date: "SAT SEP 26", opponent: "Georgia", loc: "HOME", venue: "Starkville, Miss." },
    { week: 5, date: "SAT OCT 3", opponent: "Florida", loc: "AWAY", venue: "Gainesville, Fla." },
    { week: 6, date: "SAT OCT 10", opponent: "Tennessee", loc: "AWAY", venue: "Knoxville, Tenn." },
    { week: 7, date: "SAT OCT 17", opponent: "Kentucky", loc: "HOME", venue: "Starkville, Miss." },
    { week: 8, date: "SAT OCT 31", opponent: "Auburn", loc: "AWAY", venue: "Auburn, Ala." },
    { week: 9, date: "SAT NOV 7", opponent: "Vanderbilt", loc: "HOME", venue: "Starkville, Miss." },
    { week: 10, date: "SAT NOV 14", opponent: "Missouri", loc: "AWAY", venue: "Columbia, Mo." },
    { week: 11, date: "SAT NOV 21", opponent: "South Carolina", loc: "HOME", venue: "Starkville, Miss." },
    { week: 12, date: "SAT NOV 28", opponent: "Ole Miss", loc: "AWAY", venue: "Oxford, Miss." },
  ],
  Vanderbilt: [
    { week: 1, date: "SAT SEP 5", opponent: "Elon", loc: "HOME", venue: "Nashville, Tenn." },
    { week: 2, date: "SAT SEP 12", opponent: "Virginia Tech", loc: "AWAY", venue: "Blacksburg, Va." },
    { week: 3, date: "SAT SEP 19", opponent: "New Mexico State", loc: "HOME", venue: "Nashville, Tenn." },
    { week: 4, date: "SAT SEP 26", opponent: "Alabama", loc: "HOME", venue: "Nashville, Tenn." },
    { week: 5, date: "SAT OCT 3", opponent: "South Carolina", loc: "HOME", venue: "Nashville, Tenn." },
    { week: 6, date: "SAT OCT 10", opponent: "Georgia", loc: "AWAY", venue: "Athens, Ga." },
    { week: 7, date: "SAT OCT 17", opponent: "Florida", loc: "AWAY", venue: "Gainesville, Fla." },
    { week: 8, date: "SAT OCT 31", opponent: "Texas", loc: "HOME", venue: "Nashville, Tenn." },
    { week: 9, date: "SAT NOV 7", opponent: "Mississippi State", loc: "AWAY", venue: "Starkville, Miss." },
    { week: 10, date: "SAT NOV 14", opponent: "LSU", loc: "AWAY", venue: "Baton Rouge, La." },
    { week: 11, date: "SAT NOV 21", opponent: "Ole Miss", loc: "HOME", venue: "Nashville, Tenn." },
    { week: 12, date: "SAT NOV 28", opponent: "Tennessee", loc: "HOME", venue: "Nashville, Tenn." },
  ],

  /* ===== ACC ===== */
  Clemson: [
    { week: 1, date: "SAT SEP 5", opponent: "Furman", loc: "HOME", venue: "Clemson, S.C." },
    { week: 2, date: "SAT SEP 12", opponent: "Georgia", loc: "AWAY", venue: "Athens, Ga." },
    { week: 3, date: "SAT SEP 19", opponent: "UCLA", loc: "HOME", venue: "Clemson, S.C." },
    { week: 4, date: "SAT SEP 26", opponent: "Wake Forest", loc: "AWAY", venue: "Winston-Salem, N.C." },
    { week: 5, date: "SAT OCT 3", opponent: "NC State", loc: "HOME", venue: "Clemson, S.C." },
    { week: 6, date: "SAT OCT 10", opponent: "Louisville", loc: "AWAY", venue: "Louisville, Ky." },
    { week: 7, date: "SAT OCT 17", opponent: "Virginia Tech", loc: "HOME", venue: "Clemson, S.C." },
    { week: 8, date: "SAT OCT 31", opponent: "Pitt", loc: "AWAY", venue: "Pittsburgh, Pa." },
    { week: 9, date: "SAT NOV 7", opponent: "Notre Dame", loc: "HOME", venue: "Clemson, S.C." },
    { week: 10, date: "SAT NOV 14", opponent: "Duke", loc: "HOME", venue: "Clemson, S.C." },
    { week: 11, date: "SAT NOV 21", opponent: "Georgia Tech", loc: "AWAY", venue: "Atlanta, Ga." },
    { week: 12, date: "SAT NOV 28", opponent: "South Carolina", loc: "HOME", venue: "Clemson, S.C." },
  ],
  "Notre Dame": [
    { week: 1, date: "SAT SEP 5", opponent: "Northern Illinois", loc: "HOME", venue: "South Bend, Ind." },
    { week: 2, date: "SAT SEP 12", opponent: "Army", loc: "HOME", venue: "South Bend, Ind." },
    { week: 3, date: "SAT SEP 19", opponent: "Purdue", loc: "HOME", venue: "South Bend, Ind." },
    { week: 4, date: "SAT SEP 26", opponent: "Stanford", loc: "AWAY", venue: "Stanford, Calif." },
    { week: 5, date: "SAT OCT 3", opponent: "Virginia", loc: "HOME", venue: "South Bend, Ind." },
    { week: 6, date: "SAT OCT 10", opponent: "Georgia Tech", loc: "AWAY", venue: "Atlanta, Ga." },
    { week: 7, date: "SAT OCT 17", opponent: "Duke", loc: "HOME", venue: "South Bend, Ind." },
    { week: 8, date: "SAT OCT 31", opponent: "Navy", loc: "AWAY", venue: "Annapolis, Md." },
    { week: 9, date: "SAT NOV 7", opponent: "Clemson", loc: "AWAY", venue: "Clemson, S.C." },
    { week: 10, date: "SAT NOV 14", opponent: "North Carolina", loc: "HOME", venue: "South Bend, Ind." },
    { week: 11, date: "SAT NOV 21", opponent: "SMU", loc: "AWAY", venue: "Dallas, Texas" },
    { week: 12, date: "SAT NOV 28", opponent: "USC", loc: "HOME", venue: "South Bend, Ind." },
  ],
  Miami: [
    { week: 1, date: "SAT SEP 5", opponent: "Bethune-Cookman", loc: "HOME", venue: "Miami Gardens, Fla." },
    { week: 2, date: "SAT SEP 12", opponent: "Florida", loc: "HOME", venue: "Miami Gardens, Fla." },
    { week: 3, date: "SAT SEP 19", opponent: "South Florida", loc: "HOME", venue: "Miami Gardens, Fla." },
    { week: 4, date: "SAT SEP 26", opponent: "Cal", loc: "AWAY", venue: "Berkeley, Calif." },
    { week: 5, date: "SAT OCT 3", opponent: "Virginia Tech", loc: "HOME", venue: "Miami Gardens, Fla." },
    { week: 6, date: "SAT OCT 10", opponent: "NC State", loc: "AWAY", venue: "Raleigh, N.C." },
    { week: 7, date: "SAT OCT 17", opponent: "Syracuse", loc: "HOME", venue: "Miami Gardens, Fla." },
    { week: 8, date: "SAT OCT 31", opponent: "Duke", loc: "AWAY", venue: "Durham, N.C." },
    { week: 9, date: "SAT NOV 7", opponent: "Georgia Tech", loc: "HOME", venue: "Miami Gardens, Fla." },
    { week: 10, date: "SAT NOV 14", opponent: "Wake Forest", loc: "AWAY", venue: "Winston-Salem, N.C." },
    { week: 11, date: "SAT NOV 21", opponent: "Pitt", loc: "HOME", venue: "Miami Gardens, Fla." },
    { week: 12, date: "SAT NOV 28", opponent: "Boston College", loc: "HOME", venue: "Miami Gardens, Fla." },
  ],
  "Florida State": [
    { week: 1, date: "SAT SEP 5", opponent: "Alabama", loc: "AWAY", venue: "Tuscaloosa, Ala." },
    { week: 2, date: "SAT SEP 12", opponent: "Memphis", loc: "HOME", venue: "Tallahassee, Fla." },
    { week: 3, date: "SAT SEP 19", opponent: "UConn", loc: "HOME", venue: "Tallahassee, Fla." },
    { week: 4, date: "SAT SEP 26", opponent: "SMU", loc: "AWAY", venue: "Dallas, Texas" },
    { week: 5, date: "SAT OCT 3", opponent: "North Carolina", loc: "HOME", venue: "Tallahassee, Fla." },
    { week: 6, date: "SAT OCT 10", opponent: "Duke", loc: "AWAY", venue: "Durham, N.C." },
    { week: 7, date: "SAT OCT 17", opponent: "Syracuse", loc: "HOME", venue: "Tallahassee, Fla." },
    { week: 8, date: "SAT OCT 31", opponent: "Virginia", loc: "AWAY", venue: "Charlottesville, Va." },
    { week: 9, date: "SAT NOV 7", opponent: "Pitt", loc: "HOME", venue: "Tallahassee, Fla." },
    { week: 10, date: "SAT NOV 14", opponent: "Louisville", loc: "HOME", venue: "Tallahassee, Fla." },
    { week: 11, date: "SAT NOV 21", opponent: "Boston College", loc: "AWAY", venue: "Chestnut Hill, Mass." },
    { week: 12, date: "SAT NOV 28", opponent: "Stanford", loc: "HOME", venue: "Tallahassee, Fla." },
  ],
  Louisville: [
    { week: 1, date: "SAT SEP 5", opponent: "Austin Peay", loc: "HOME", venue: "Louisville, Ky." },
    { week: 2, date: "SAT SEP 12", opponent: "Kentucky", loc: "HOME", venue: "Louisville, Ky." },
    { week: 3, date: "SAT SEP 19", opponent: "Indiana", loc: "HOME", venue: "Louisville, Ky." },
    { week: 4, date: "SAT SEP 26", opponent: "Virginia", loc: "AWAY", venue: "Charlottesville, Va." },
    { week: 5, date: "SAT OCT 3", opponent: "Pitt", loc: "HOME", venue: "Louisville, Ky." },
    { week: 6, date: "SAT OCT 10", opponent: "Clemson", loc: "HOME", venue: "Louisville, Ky." },
    { week: 7, date: "SAT OCT 17", opponent: "Stanford", loc: "AWAY", venue: "Stanford, Calif." },
    { week: 8, date: "SAT OCT 31", opponent: "Boston College", loc: "AWAY", venue: "Chestnut Hill, Mass." },
    { week: 9, date: "SAT NOV 7", opponent: "Syracuse", loc: "HOME", venue: "Louisville, Ky." },
    { week: 10, date: "SAT NOV 14", opponent: "Florida State", loc: "AWAY", venue: "Tallahassee, Fla." },
    { week: 11, date: "SAT NOV 21", opponent: "NC State", loc: "HOME", venue: "Louisville, Ky." },
    { week: 12, date: "SAT NOV 28", opponent: "Virginia Tech", loc: "HOME", venue: "Louisville, Ky." },
  ],
  SMU: [
    { week: 1, date: "SAT SEP 5", opponent: "North Texas", loc: "HOME", venue: "Dallas, Texas" },
    { week: 2, date: "SAT SEP 12", opponent: "TCU", loc: "AWAY", venue: "Fort Worth, Texas" },
    { week: 3, date: "SAT SEP 19", opponent: "UTSA", loc: "HOME", venue: "Dallas, Texas" },
    { week: 4, date: "SAT SEP 26", opponent: "Florida State", loc: "HOME", venue: "Dallas, Texas" },
    { week: 5, date: "SAT OCT 3", opponent: "Cal", loc: "AWAY", venue: "Berkeley, Calif." },
    { week: 6, date: "SAT OCT 10", opponent: "Stanford", loc: "HOME", venue: "Dallas, Texas" },
    { week: 7, date: "SAT OCT 17", opponent: "Wake Forest", loc: "AWAY", venue: "Winston-Salem, N.C." },
    { week: 8, date: "SAT OCT 31", opponent: "North Carolina", loc: "HOME", venue: "Dallas, Texas" },
    { week: 9, date: "SAT NOV 7", opponent: "Virginia", loc: "AWAY", venue: "Charlottesville, Va." },
    { week: 10, date: "SAT NOV 14", opponent: "Pitt", loc: "HOME", venue: "Dallas, Texas" },
    { week: 11, date: "SAT NOV 21", opponent: "Notre Dame", loc: "HOME", venue: "Dallas, Texas" },
    { week: 12, date: "SAT NOV 28", opponent: "Duke", loc: "AWAY", venue: "Durham, N.C." },
  ],
  Pitt: [
    { week: 1, date: "SAT SEP 5", opponent: "Youngstown State", loc: "HOME", venue: "Pittsburgh, Pa." },
    { week: 2, date: "SAT SEP 12", opponent: "Cincinnati", loc: "HOME", venue: "Pittsburgh, Pa." },
    { week: 3, date: "SAT SEP 19", opponent: "Kent State", loc: "HOME", venue: "Pittsburgh, Pa." },
    { week: 4, date: "SAT SEP 26", opponent: "North Carolina", loc: "AWAY", venue: "Chapel Hill, N.C." },
    { week: 5, date: "SAT OCT 3", opponent: "Louisville", loc: "AWAY", venue: "Louisville, Ky." },
    { week: 6, date: "SAT OCT 10", opponent: "Syracuse", loc: "HOME", venue: "Pittsburgh, Pa." },
    { week: 7, date: "SAT OCT 17", opponent: "Cal", loc: "HOME", venue: "Pittsburgh, Pa." },
    { week: 8, date: "SAT OCT 31", opponent: "Clemson", loc: "HOME", venue: "Pittsburgh, Pa." },
    { week: 9, date: "SAT NOV 7", opponent: "Florida State", loc: "AWAY", venue: "Tallahassee, Fla." },
    { week: 10, date: "SAT NOV 14", opponent: "SMU", loc: "AWAY", venue: "Dallas, Texas" },
    { week: 11, date: "SAT NOV 21", opponent: "Miami", loc: "AWAY", venue: "Miami Gardens, Fla." },
    { week: 12, date: "SAT NOV 28", opponent: "Virginia Tech", loc: "HOME", venue: "Pittsburgh, Pa." },
  ],
  Duke: [
    { week: 1, date: "SAT SEP 5", opponent: "Elon", loc: "HOME", venue: "Durham, N.C." },
    { week: 2, date: "SAT SEP 12", opponent: "Northwestern", loc: "AWAY", venue: "Evanston, Ill." },
    { week: 3, date: "SAT SEP 19", opponent: "North Carolina Central", loc: "HOME", venue: "Durham, N.C." },
    { week: 4, date: "SAT SEP 26", opponent: "Georgia Tech", loc: "HOME", venue: "Durham, N.C." },
    { week: 5, date: "SAT OCT 3", opponent: "Wake Forest", loc: "AWAY", venue: "Winston-Salem, N.C." },
    { week: 6, date: "SAT OCT 10", opponent: "Florida State", loc: "HOME", venue: "Durham, N.C." },
    { week: 7, date: "SAT OCT 17", opponent: "Notre Dame", loc: "AWAY", venue: "South Bend, Ind." },
    { week: 8, date: "SAT OCT 31", opponent: "Miami", loc: "HOME", venue: "Durham, N.C." },
    { week: 9, date: "SAT NOV 7", opponent: "Virginia", loc: "AWAY", venue: "Charlottesville, Va." },
    { week: 10, date: "SAT NOV 14", opponent: "Clemson", loc: "AWAY", venue: "Clemson, S.C." },
    { week: 11, date: "SAT NOV 21", opponent: "Virginia Tech", loc: "HOME", venue: "Durham, N.C." },
    { week: 12, date: "SAT NOV 28", opponent: "SMU", loc: "HOME", venue: "Durham, N.C." },
  ],
  "North Carolina": [
    { week: 1, date: "SAT SEP 5", opponent: "Elon", loc: "HOME", venue: "Chapel Hill, N.C." },
    { week: 2, date: "SAT SEP 12", opponent: "Charlotte", loc: "HOME", venue: "Chapel Hill, N.C." },
    { week: 3, date: "SAT SEP 19", opponent: "App State", loc: "HOME", venue: "Chapel Hill, N.C." },
    { week: 4, date: "SAT SEP 26", opponent: "Pitt", loc: "HOME", venue: "Chapel Hill, N.C." },
    { week: 5, date: "SAT OCT 3", opponent: "Florida State", loc: "AWAY", venue: "Tallahassee, Fla." },
    { week: 6, date: "SAT OCT 10", opponent: "Virginia", loc: "HOME", venue: "Chapel Hill, N.C." },
    { week: 7, date: "SAT OCT 17", opponent: "Georgia Tech", loc: "AWAY", venue: "Atlanta, Ga." },
    { week: 8, date: "SAT OCT 31", opponent: "SMU", loc: "AWAY", venue: "Dallas, Texas" },
    { week: 9, date: "SAT NOV 7", opponent: "Wake Forest", loc: "HOME", venue: "Chapel Hill, N.C." },
    { week: 10, date: "SAT NOV 14", opponent: "Notre Dame", loc: "AWAY", venue: "South Bend, Ind." },
    { week: 11, date: "SAT NOV 21", opponent: "NC State", loc: "AWAY", venue: "Raleigh, N.C." },
    { week: 12, date: "SAT NOV 28", opponent: "Virginia Tech", loc: "HOME", venue: "Chapel Hill, N.C." },
  ],
  "NC State": [
    { week: 1, date: "SAT SEP 5", opponent: "East Carolina", loc: "HOME", venue: "Raleigh, N.C." },
    { week: 2, date: "SAT SEP 12", opponent: "Tennessee", loc: "AWAY", venue: "Knoxville, Tenn." },
    { week: 3, date: "SAT SEP 19", opponent: "UConn", loc: "HOME", venue: "Raleigh, N.C." },
    { week: 4, date: "SAT SEP 26", opponent: "Syracuse", loc: "HOME", venue: "Raleigh, N.C." },
    { week: 5, date: "SAT OCT 3", opponent: "Clemson", loc: "AWAY", venue: "Clemson, S.C." },
    { week: 6, date: "SAT OCT 10", opponent: "Miami", loc: "HOME", venue: "Raleigh, N.C." },
    { week: 7, date: "SAT OCT 17", opponent: "Cal", loc: "AWAY", venue: "Berkeley, Calif." },
    { week: 8, date: "SAT OCT 31", opponent: "Stanford", loc: "HOME", venue: "Raleigh, N.C." },
    { week: 9, date: "SAT NOV 7", opponent: "Boston College", loc: "AWAY", venue: "Chestnut Hill, Mass." },
    { week: 10, date: "SAT NOV 14", opponent: "Virginia Tech", loc: "HOME", venue: "Raleigh, N.C." },
    { week: 11, date: "SAT NOV 21", opponent: "North Carolina", loc: "HOME", venue: "Raleigh, N.C." },
    { week: 12, date: "SAT NOV 28", opponent: "Wake Forest", loc: "AWAY", venue: "Winston-Salem, N.C." },
  ],
  Syracuse: [
    { week: 1, date: "SAT SEP 5", opponent: "Colgate", loc: "HOME", venue: "Syracuse, N.Y." },
    { week: 2, date: "SAT SEP 12", opponent: "Army", loc: "HOME", venue: "Syracuse, N.Y." },
    { week: 3, date: "SAT SEP 19", opponent: "Liberty", loc: "HOME", venue: "Syracuse, N.Y." },
    { week: 4, date: "SAT SEP 26", opponent: "NC State", loc: "AWAY", venue: "Raleigh, N.C." },
    { week: 5, date: "SAT OCT 3", opponent: "Stanford", loc: "HOME", venue: "Syracuse, N.Y." },
    { week: 6, date: "SAT OCT 10", opponent: "Pitt", loc: "AWAY", venue: "Pittsburgh, Pa." },
    { week: 7, date: "SAT OCT 17", opponent: "Miami", loc: "AWAY", venue: "Miami Gardens, Fla." },
    { week: 8, date: "SAT OCT 31", opponent: "Virginia Tech", loc: "HOME", venue: "Syracuse, N.Y." },
    { week: 9, date: "SAT NOV 7", opponent: "Louisville", loc: "AWAY", venue: "Louisville, Ky." },
    { week: 10, date: "SAT NOV 14", opponent: "Cal", loc: "HOME", venue: "Syracuse, N.Y." },
    { week: 11, date: "SAT NOV 21", opponent: "Wake Forest", loc: "HOME", venue: "Syracuse, N.Y." },
    { week: 12, date: "SAT NOV 28", opponent: "Boston College", loc: "AWAY", venue: "Chestnut Hill, Mass." },
  ],
  Virginia: [
    { week: 1, date: "SAT SEP 5", opponent: "Richmond", loc: "HOME", venue: "Charlottesville, Va." },
    { week: 2, date: "SAT SEP 12", opponent: "Old Dominion", loc: "HOME", venue: "Charlottesville, Va." },
    { week: 3, date: "SAT SEP 19", opponent: "Maryland", loc: "HOME", venue: "Charlottesville, Va." },
    { week: 4, date: "SAT SEP 26", opponent: "Louisville", loc: "HOME", venue: "Charlottesville, Va." },
    { week: 5, date: "SAT OCT 3", opponent: "Notre Dame", loc: "AWAY", venue: "South Bend, Ind." },
    { week: 6, date: "SAT OCT 10", opponent: "North Carolina", loc: "AWAY", venue: "Chapel Hill, N.C." },
    { week: 7, date: "SAT OCT 17", opponent: "Boston College", loc: "HOME", venue: "Charlottesville, Va." },
    { week: 8, date: "SAT OCT 31", opponent: "Florida State", loc: "HOME", venue: "Charlottesville, Va." },
    { week: 9, date: "SAT NOV 7", opponent: "SMU", loc: "HOME", venue: "Charlottesville, Va." },
    { week: 10, date: "SAT NOV 14", opponent: "Georgia Tech", loc: "AWAY", venue: "Atlanta, Ga." },
    { week: 11, date: "SAT NOV 21", opponent: "Wake Forest", loc: "AWAY", venue: "Winston-Salem, N.C." },
    { week: 12, date: "SAT NOV 28", opponent: "Virginia Tech", loc: "AWAY", venue: "Blacksburg, Va." },
  ],
  "Virginia Tech": [
    { week: 1, date: "SAT SEP 5", opponent: "Old Dominion", loc: "HOME", venue: "Blacksburg, Va." },
    { week: 2, date: "SAT SEP 12", opponent: "Vanderbilt", loc: "HOME", venue: "Blacksburg, Va." },
    { week: 3, date: "SAT SEP 19", opponent: "Marshall", loc: "HOME", venue: "Blacksburg, Va." },
    { week: 4, date: "SAT SEP 26", opponent: "Boston College", loc: "AWAY", venue: "Chestnut Hill, Mass." },
    { week: 5, date: "SAT OCT 3", opponent: "Miami", loc: "AWAY", venue: "Miami Gardens, Fla." },
    { week: 6, date: "SAT OCT 10", opponent: "Wake Forest", loc: "HOME", venue: "Blacksburg, Va." },
    { week: 7, date: "SAT OCT 17", opponent: "Clemson", loc: "AWAY", venue: "Clemson, S.C." },
    { week: 8, date: "SAT OCT 31", opponent: "Syracuse", loc: "AWAY", venue: "Syracuse, N.Y." },
    { week: 9, date: "SAT NOV 7", opponent: "Georgia Tech", loc: "HOME", venue: "Blacksburg, Va." },
    { week: 10, date: "SAT NOV 14", opponent: "NC State", loc: "AWAY", venue: "Raleigh, N.C." },
    { week: 11, date: "SAT NOV 21", opponent: "Duke", loc: "AWAY", venue: "Durham, N.C." },
    { week: 12, date: "SAT NOV 28", opponent: "Virginia", loc: "HOME", venue: "Blacksburg, Va." },
  ],
  "Georgia Tech": [
    { week: 1, date: "SAT SEP 5", opponent: "Kennesaw State", loc: "HOME", venue: "Atlanta, Ga." },
    { week: 2, date: "SAT SEP 12", opponent: "Georgia Southern", loc: "HOME", venue: "Atlanta, Ga." },
    { week: 3, date: "SAT SEP 19", opponent: "Troy", loc: "HOME", venue: "Atlanta, Ga." },
    { week: 4, date: "SAT SEP 26", opponent: "Duke", loc: "AWAY", venue: "Durham, N.C." },
    { week: 5, date: "SAT OCT 3", opponent: "Boston College", loc: "HOME", venue: "Atlanta, Ga." },
    { week: 6, date: "SAT OCT 10", opponent: "Notre Dame", loc: "HOME", venue: "Atlanta, Ga." },
    { week: 7, date: "SAT OCT 17", opponent: "North Carolina", loc: "HOME", venue: "Atlanta, Ga." },
    { week: 8, date: "SAT OCT 31", opponent: "Cal", loc: "AWAY", venue: "Berkeley, Calif." },
    { week: 9, date: "SAT NOV 7", opponent: "Miami", loc: "AWAY", venue: "Miami Gardens, Fla." },
    { week: 10, date: "SAT NOV 14", opponent: "Virginia", loc: "HOME", venue: "Atlanta, Ga." },
    { week: 11, date: "SAT NOV 21", opponent: "Clemson", loc: "HOME", venue: "Atlanta, Ga." },
    { week: 12, date: "SAT NOV 28", opponent: "Georgia", loc: "AWAY", venue: "Athens, Ga." },
  ],
  "Wake Forest": [
    { week: 1, date: "SAT SEP 5", opponent: "VMI", loc: "HOME", venue: "Winston-Salem, N.C." },
    { week: 2, date: "SAT SEP 12", opponent: "Ole Miss", loc: "AWAY", venue: "Oxford, Miss." },
    { week: 3, date: "SAT SEP 19", opponent: "William & Mary", loc: "HOME", venue: "Winston-Salem, N.C." },
    { week: 4, date: "SAT SEP 26", opponent: "Clemson", loc: "HOME", venue: "Winston-Salem, N.C." },
    { week: 5, date: "SAT OCT 3", opponent: "Duke", loc: "HOME", venue: "Winston-Salem, N.C." },
    { week: 6, date: "SAT OCT 10", opponent: "Virginia Tech", loc: "AWAY", venue: "Blacksburg, Va." },
    { week: 7, date: "SAT OCT 17", opponent: "SMU", loc: "HOME", venue: "Winston-Salem, N.C." },
    { week: 8, date: "SAT OCT 31", opponent: "Stanford", loc: "AWAY", venue: "Stanford, Calif." },
    { week: 9, date: "SAT NOV 7", opponent: "North Carolina", loc: "AWAY", venue: "Chapel Hill, N.C." },
    { week: 10, date: "SAT NOV 14", opponent: "Miami", loc: "HOME", venue: "Winston-Salem, N.C." },
    { week: 11, date: "SAT NOV 21", opponent: "Virginia", loc: "HOME", venue: "Winston-Salem, N.C." },
    { week: 12, date: "SAT NOV 28", opponent: "NC State", loc: "HOME", venue: "Winston-Salem, N.C." },
  ],
  "Boston College": [
    { week: 1, date: "SAT SEP 5", opponent: "Maine", loc: "HOME", venue: "Chestnut Hill, Mass." },
    { week: 2, date: "SAT SEP 12", opponent: "UMass", loc: "HOME", venue: "Chestnut Hill, Mass." },
    { week: 3, date: "SAT SEP 19", opponent: "Missouri", loc: "HOME", venue: "Chestnut Hill, Mass." },
    { week: 4, date: "SAT SEP 26", opponent: "Virginia Tech", loc: "HOME", venue: "Chestnut Hill, Mass." },
    { week: 5, date: "SAT OCT 3", opponent: "Georgia Tech", loc: "AWAY", venue: "Atlanta, Ga." },
    { week: 6, date: "SAT OCT 10", opponent: "Cal", loc: "HOME", venue: "Chestnut Hill, Mass." },
    { week: 7, date: "SAT OCT 17", opponent: "Virginia", loc: "AWAY", venue: "Charlottesville, Va." },
    { week: 8, date: "SAT OCT 31", opponent: "Louisville", loc: "HOME", venue: "Chestnut Hill, Mass." },
    { week: 9, date: "SAT NOV 7", opponent: "NC State", loc: "HOME", venue: "Chestnut Hill, Mass." },
    { week: 10, date: "SAT NOV 14", opponent: "Stanford", loc: "AWAY", venue: "Stanford, Calif." },
    { week: 11, date: "SAT NOV 21", opponent: "Florida State", loc: "HOME", venue: "Chestnut Hill, Mass." },
    { week: 12, date: "SAT NOV 28", opponent: "Miami", loc: "AWAY", venue: "Miami Gardens, Fla." },
  ],
  Cal: [
    { week: 1, date: "SAT SEP 5", opponent: "UC Davis", loc: "HOME", venue: "Berkeley, Calif." },
    { week: 2, date: "SAT SEP 12", opponent: "Auburn", loc: "AWAY", venue: "Auburn, Ala." },
    { week: 3, date: "SAT SEP 19", opponent: "San Jose State", loc: "HOME", venue: "Berkeley, Calif." },
    { week: 4, date: "SAT SEP 26", opponent: "Miami", loc: "HOME", venue: "Berkeley, Calif." },
    { week: 5, date: "SAT OCT 3", opponent: "SMU", loc: "HOME", venue: "Berkeley, Calif." },
    { week: 6, date: "SAT OCT 10", opponent: "Boston College", loc: "AWAY", venue: "Chestnut Hill, Mass." },
    { week: 7, date: "SAT OCT 17", opponent: "NC State", loc: "HOME", venue: "Berkeley, Calif." },
    { week: 8, date: "SAT OCT 31", opponent: "Georgia Tech", loc: "HOME", venue: "Berkeley, Calif." },
    { week: 9, date: "SAT NOV 7", opponent: "Stanford", loc: "AWAY", venue: "Stanford, Calif." },
    { week: 10, date: "SAT NOV 14", opponent: "Syracuse", loc: "AWAY", venue: "Syracuse, N.Y." },
    { week: 11, date: "SAT NOV 21", opponent: "Stanford", loc: "HOME", venue: "Berkeley, Calif." },
    { week: 12, date: "SAT NOV 28", opponent: "Pitt", loc: "AWAY", venue: "Pittsburgh, Pa." },
  ],
  Stanford: [
    { week: 1, date: "SAT SEP 5", opponent: "Sacramento State", loc: "HOME", venue: "Stanford, Calif." },
    { week: 2, date: "SAT SEP 12", opponent: "San Jose State", loc: "HOME", venue: "Stanford, Calif." },
    { week: 3, date: "SAT SEP 19", opponent: "BYU", loc: "AWAY", venue: "Provo, Utah" },
    { week: 4, date: "SAT SEP 26", opponent: "Notre Dame", loc: "HOME", venue: "Stanford, Calif." },
    { week: 5, date: "SAT OCT 3", opponent: "Syracuse", loc: "AWAY", venue: "Syracuse, N.Y." },
    { week: 6, date: "SAT OCT 10", opponent: "SMU", loc: "AWAY", venue: "Dallas, Texas" },
    { week: 7, date: "SAT OCT 17", opponent: "Louisville", loc: "HOME", venue: "Stanford, Calif." },
    { week: 8, date: "SAT OCT 31", opponent: "Wake Forest", loc: "HOME", venue: "Stanford, Calif." },
    { week: 9, date: "SAT NOV 7", opponent: "Cal", loc: "HOME", venue: "Stanford, Calif." },
    { week: 10, date: "SAT NOV 14", opponent: "Boston College", loc: "HOME", venue: "Stanford, Calif." },
    { week: 11, date: "SAT NOV 21", opponent: "Cal", loc: "AWAY", venue: "Berkeley, Calif." },
    { week: 12, date: "SAT NOV 28", opponent: "Florida State", loc: "AWAY", venue: "Tallahassee, Fla." },
  ],

  /* ===== BIG 12 ===== */
  Colorado: [
    { week: 1, date: "SAT SEP 5", opponent: "North Dakota State", loc: "HOME", venue: "Boulder, Colo." },
    { week: 2, date: "SAT SEP 12", opponent: "Nebraska", loc: "HOME", venue: "Boulder, Colo." },
    { week: 3, date: "SAT SEP 19", opponent: "Minnesota", loc: "HOME", venue: "Boulder, Colo." },
    { week: 4, date: "SAT SEP 26", opponent: "TCU", loc: "AWAY", venue: "Fort Worth, Texas" },
    { week: 5, date: "SAT OCT 3", opponent: "Arizona State", loc: "HOME", venue: "Boulder, Colo." },
    { week: 6, date: "SAT OCT 10", opponent: "Kansas", loc: "AWAY", venue: "Lawrence, Kan." },
    { week: 7, date: "SAT OCT 17", opponent: "Texas Tech", loc: "HOME", venue: "Boulder, Colo." },
    { week: 8, date: "SAT OCT 31", opponent: "Oklahoma State", loc: "AWAY", venue: "Stillwater, Okla." },
    { week: 9, date: "SAT NOV 7", opponent: "Cincinnati", loc: "HOME", venue: "Boulder, Colo." },
    { week: 10, date: "SAT NOV 14", opponent: "BYU", loc: "AWAY", venue: "Provo, Utah" },
    { week: 11, date: "SAT NOV 21", opponent: "Utah", loc: "HOME", venue: "Boulder, Colo." },
    { week: 12, date: "SAT NOV 28", opponent: "Iowa State", loc: "AWAY", venue: "Ames, Iowa" },
  ],
  Arizona: [
    { week: 1, date: "SAT SEP 5", opponent: "Northern Arizona", loc: "HOME", venue: "Tucson, Ariz." },
    { week: 2, date: "SAT SEP 12", opponent: "Washington", loc: "AWAY", venue: "Seattle, Wash." },
    { week: 3, date: "SAT SEP 19", opponent: "UTEP", loc: "HOME", venue: "Tucson, Ariz." },
    { week: 4, date: "SAT SEP 26", opponent: "Kansas State", loc: "HOME", venue: "Tucson, Ariz." },
    { week: 5, date: "SAT OCT 3", opponent: "UCF", loc: "AWAY", venue: "Orlando, Fla." },
    { week: 6, date: "SAT OCT 10", opponent: "Houston", loc: "HOME", venue: "Tucson, Ariz." },
    { week: 7, date: "SAT OCT 17", opponent: "BYU", loc: "AWAY", venue: "Provo, Utah" },
    { week: 8, date: "SAT OCT 31", opponent: "Baylor", loc: "HOME", venue: "Tucson, Ariz." },
    { week: 9, date: "SAT NOV 7", opponent: "West Virginia", loc: "HOME", venue: "Tucson, Ariz." },
    { week: 10, date: "SAT NOV 14", opponent: "Utah", loc: "AWAY", venue: "Salt Lake City, Utah" },
    { week: 11, date: "SAT NOV 21", opponent: "Iowa State", loc: "HOME", venue: "Tucson, Ariz." },
    { week: 12, date: "SAT NOV 28", opponent: "Arizona State", loc: "AWAY", venue: "Tempe, Ariz." },
  ],
  "Arizona State": [
    { week: 1, date: "SAT SEP 5", opponent: "Southern Utah", loc: "HOME", venue: "Tempe, Ariz." },
    { week: 2, date: "SAT SEP 12", opponent: "Texas State", loc: "HOME", venue: "Tempe, Ariz." },
    { week: 3, date: "SAT SEP 19", opponent: "Oklahoma State", loc: "HOME", venue: "Tempe, Ariz." },
    { week: 4, date: "SAT SEP 26", opponent: "Utah", loc: "AWAY", venue: "Salt Lake City, Utah" },
    { week: 5, date: "SAT OCT 3", opponent: "Colorado", loc: "AWAY", venue: "Boulder, Colo." },
    { week: 6, date: "SAT OCT 10", opponent: "Baylor", loc: "HOME", venue: "Tempe, Ariz." },
    { week: 7, date: "SAT OCT 17", opponent: "Cincinnati", loc: "AWAY", venue: "Cincinnati, Ohio" },
    { week: 8, date: "SAT OCT 31", opponent: "Kansas State", loc: "HOME", venue: "Tempe, Ariz." },
    { week: 9, date: "SAT NOV 7", opponent: "TCU", loc: "AWAY", venue: "Fort Worth, Texas" },
    { week: 10, date: "SAT NOV 14", opponent: "Kansas", loc: "HOME", venue: "Tempe, Ariz." },
    { week: 11, date: "SAT NOV 21", opponent: "BYU", loc: "HOME", venue: "Tempe, Ariz." },
    { week: 12, date: "SAT NOV 28", opponent: "Arizona", loc: "HOME", venue: "Tempe, Ariz." },
  ],
  BYU: [
    { week: 1, date: "SAT SEP 5", opponent: "Idaho", loc: "HOME", venue: "Provo, Utah" },
    { week: 2, date: "SAT SEP 12", opponent: "Utah State", loc: "HOME", venue: "Provo, Utah" },
    { week: 3, date: "SAT SEP 19", opponent: "Stanford", loc: "HOME", venue: "Provo, Utah" },
    { week: 4, date: "SAT SEP 26", opponent: "Iowa State", loc: "AWAY", venue: "Ames, Iowa" },
    { week: 5, date: "SAT OCT 3", opponent: "Kansas", loc: "HOME", venue: "Provo, Utah" },
    { week: 6, date: "SAT OCT 10", opponent: "West Virginia", loc: "AWAY", venue: "Morgantown, W.Va." },
    { week: 7, date: "SAT OCT 17", opponent: "Arizona", loc: "HOME", venue: "Provo, Utah" },
    { week: 8, date: "SAT OCT 31", opponent: "UCF", loc: "AWAY", venue: "Orlando, Fla." },
    { week: 9, date: "SAT NOV 7", opponent: "Houston", loc: "HOME", venue: "Provo, Utah" },
    { week: 10, date: "SAT NOV 14", opponent: "Colorado", loc: "HOME", venue: "Provo, Utah" },
    { week: 11, date: "SAT NOV 21", opponent: "Arizona State", loc: "AWAY", venue: "Tempe, Ariz." },
    { week: 12, date: "SAT NOV 28", opponent: "Utah", loc: "HOME", venue: "Provo, Utah" },
  ],
  Baylor: [
    { week: 1, date: "SAT SEP 5", opponent: "Tarleton State", loc: "HOME", venue: "Waco, Texas" },
    { week: 2, date: "SAT SEP 12", opponent: "Texas A&M", loc: "AWAY", venue: "College Station, Texas" },
    { week: 3, date: "SAT SEP 19", opponent: "Air Force", loc: "HOME", venue: "Waco, Texas" },
    { week: 4, date: "SAT SEP 26", opponent: "West Virginia", loc: "HOME", venue: "Waco, Texas" },
    { week: 5, date: "SAT OCT 3", opponent: "Oklahoma State", loc: "AWAY", venue: "Stillwater, Okla." },
    { week: 6, date: "SAT OCT 10", opponent: "Arizona State", loc: "AWAY", venue: "Tempe, Ariz." },
    { week: 7, date: "SAT OCT 17", opponent: "Kansas State", loc: "HOME", venue: "Waco, Texas" },
    { week: 8, date: "SAT OCT 31", opponent: "Arizona", loc: "AWAY", venue: "Tucson, Ariz." },
    { week: 9, date: "SAT NOV 7", opponent: "Iowa State", loc: "HOME", venue: "Waco, Texas" },
    { week: 10, date: "SAT NOV 14", opponent: "Texas Tech", loc: "AWAY", venue: "Lubbock, Texas" },
    { week: 11, date: "SAT NOV 21", opponent: "Houston", loc: "HOME", venue: "Waco, Texas" },
    { week: 12, date: "SAT NOV 28", opponent: "TCU", loc: "AWAY", venue: "Fort Worth, Texas" },
  ],
  Cincinnati: [
    { week: 1, date: "SAT SEP 5", opponent: "Akron", loc: "HOME", venue: "Cincinnati, Ohio" },
    { week: 2, date: "SAT SEP 12", opponent: "Pitt", loc: "AWAY", venue: "Pittsburgh, Pa." },
    { week: 3, date: "SAT SEP 19", opponent: "Miami (OH)", loc: "HOME", venue: "Cincinnati, Ohio" },
    { week: 4, date: "SAT SEP 26", opponent: "Kansas", loc: "AWAY", venue: "Lawrence, Kan." },
    { week: 5, date: "SAT OCT 3", opponent: "Iowa State", loc: "HOME", venue: "Cincinnati, Ohio" },
    { week: 6, date: "SAT OCT 10", opponent: "UCF", loc: "AWAY", venue: "Orlando, Fla." },
    { week: 7, date: "SAT OCT 17", opponent: "Arizona State", loc: "HOME", venue: "Cincinnati, Ohio" },
    { week: 8, date: "SAT OCT 31", opponent: "Houston", loc: "AWAY", venue: "Houston, Texas" },
    { week: 9, date: "SAT NOV 7", opponent: "Colorado", loc: "AWAY", venue: "Boulder, Colo." },
    { week: 10, date: "SAT NOV 14", opponent: "Oklahoma State", loc: "HOME", venue: "Cincinnati, Ohio" },
    { week: 11, date: "SAT NOV 21", opponent: "West Virginia", loc: "HOME", venue: "Cincinnati, Ohio" },
    { week: 12, date: "SAT NOV 28", opponent: "TCU", loc: "HOME", venue: "Cincinnati, Ohio" },
  ],
  Houston: [
    { week: 1, date: "SAT SEP 5", opponent: "Rice", loc: "HOME", venue: "Houston, Texas" },
    { week: 2, date: "SAT SEP 12", opponent: "UTSA", loc: "HOME", venue: "Houston, Texas" },
    { week: 3, date: "SAT SEP 19", opponent: "Sam Houston", loc: "HOME", venue: "Houston, Texas" },
    { week: 4, date: "SAT SEP 26", opponent: "TCU", loc: "AWAY", venue: "Fort Worth, Texas" },
    { week: 5, date: "SAT OCT 3", opponent: "Texas Tech", loc: "HOME", venue: "Houston, Texas" },
    { week: 6, date: "SAT OCT 10", opponent: "Arizona", loc: "AWAY", venue: "Tucson, Ariz." },
    { week: 7, date: "SAT OCT 17", opponent: "UCF", loc: "HOME", venue: "Houston, Texas" },
    { week: 8, date: "SAT OCT 31", opponent: "Cincinnati", loc: "HOME", venue: "Houston, Texas" },
    { week: 9, date: "SAT NOV 7", opponent: "BYU", loc: "AWAY", venue: "Provo, Utah" },
    { week: 10, date: "SAT NOV 14", opponent: "West Virginia", loc: "AWAY", venue: "Morgantown, W.Va." },
    { week: 11, date: "SAT NOV 21", opponent: "Baylor", loc: "AWAY", venue: "Waco, Texas" },
    { week: 12, date: "SAT NOV 28", opponent: "Kansas State", loc: "HOME", venue: "Houston, Texas" },
  ],
  "Iowa State": [
    { week: 1, date: "SAT SEP 5", opponent: "Northern Iowa", loc: "HOME", venue: "Ames, Iowa" },
    { week: 2, date: "SAT SEP 12", opponent: "Iowa", loc: "HOME", venue: "Ames, Iowa" },
    { week: 3, date: "SAT SEP 19", opponent: "UNLV", loc: "HOME", venue: "Ames, Iowa" },
    { week: 4, date: "SAT SEP 26", opponent: "BYU", loc: "HOME", venue: "Ames, Iowa" },
    { week: 5, date: "SAT OCT 3", opponent: "Cincinnati", loc: "AWAY", venue: "Cincinnati, Ohio" },
    { week: 6, date: "SAT OCT 10", opponent: "Oklahoma State", loc: "HOME", venue: "Ames, Iowa" },
    { week: 7, date: "SAT OCT 17", opponent: "Utah", loc: "AWAY", venue: "Salt Lake City, Utah" },
    { week: 8, date: "SAT OCT 31", opponent: "Texas Tech", loc: "HOME", venue: "Ames, Iowa" },
    { week: 9, date: "SAT NOV 7", opponent: "Baylor", loc: "AWAY", venue: "Waco, Texas" },
    { week: 10, date: "SAT NOV 14", opponent: "UCF", loc: "HOME", venue: "Ames, Iowa" },
    { week: 11, date: "SAT NOV 21", opponent: "Arizona", loc: "AWAY", venue: "Tucson, Ariz." },
    { week: 12, date: "SAT NOV 28", opponent: "Colorado", loc: "HOME", venue: "Ames, Iowa" },
  ],
  Kansas: [
    { week: 1, date: "SAT SEP 5", opponent: "South Dakota", loc: "HOME", venue: "Lawrence, Kan." },
    { week: 2, date: "SAT SEP 12", opponent: "Illinois", loc: "HOME", venue: "Lawrence, Kan." },
    { week: 3, date: "SAT SEP 19", opponent: "Louisiana", loc: "HOME", venue: "Lawrence, Kan." },
    { week: 4, date: "SAT SEP 26", opponent: "Cincinnati", loc: "HOME", venue: "Lawrence, Kan." },
    { week: 5, date: "SAT OCT 3", opponent: "BYU", loc: "AWAY", venue: "Provo, Utah" },
    { week: 6, date: "SAT OCT 10", opponent: "Colorado", loc: "HOME", venue: "Lawrence, Kan." },
    { week: 7, date: "SAT OCT 17", opponent: "Oklahoma State", loc: "AWAY", venue: "Stillwater, Okla." },
    { week: 8, date: "SAT OCT 31", opponent: "UCF", loc: "HOME", venue: "Lawrence, Kan." },
    { week: 9, date: "SAT NOV 7", opponent: "Texas Tech", loc: "AWAY", venue: "Lubbock, Texas" },
    { week: 10, date: "SAT NOV 14", opponent: "Arizona State", loc: "AWAY", venue: "Tempe, Ariz." },
    { week: 11, date: "SAT NOV 21", opponent: "Kansas State", loc: "HOME", venue: "Lawrence, Kan." },
    { week: 12, date: "SAT NOV 28", opponent: "Missouri", loc: "HOME", venue: "Lawrence, Kan." },
  ],
  "Kansas State": [
    { week: 1, date: "SAT SEP 5", opponent: "South Dakota State", loc: "HOME", venue: "Manhattan, Kan." },
    { week: 2, date: "SAT SEP 12", opponent: "Tulsa", loc: "HOME", venue: "Manhattan, Kan." },
    { week: 3, date: "SAT SEP 19", opponent: "Missouri State", loc: "HOME", venue: "Manhattan, Kan." },
    { week: 4, date: "SAT SEP 26", opponent: "Arizona", loc: "AWAY", venue: "Tucson, Ariz." },
    { week: 5, date: "SAT OCT 3", opponent: "West Virginia", loc: "HOME", venue: "Manhattan, Kan." },
    { week: 6, date: "SAT OCT 10", opponent: "TCU", loc: "AWAY", venue: "Fort Worth, Texas" },
    { week: 7, date: "SAT OCT 17", opponent: "Baylor", loc: "AWAY", venue: "Waco, Texas" },
    { week: 8, date: "SAT OCT 31", opponent: "Arizona State", loc: "AWAY", venue: "Tempe, Ariz." },
    { week: 9, date: "SAT NOV 7", opponent: "Utah", loc: "HOME", venue: "Manhattan, Kan." },
    { week: 10, date: "SAT NOV 14", opponent: "Texas Tech", loc: "HOME", venue: "Manhattan, Kan." },
    { week: 11, date: "SAT NOV 21", opponent: "Kansas", loc: "AWAY", venue: "Lawrence, Kan." },
    { week: 12, date: "SAT NOV 28", opponent: "Houston", loc: "AWAY", venue: "Houston, Texas" },
  ],
  "Oklahoma State": [
    { week: 1, date: "SAT SEP 5", opponent: "Central Arkansas", loc: "HOME", venue: "Stillwater, Okla." },
    { week: 2, date: "SAT SEP 12", opponent: "Arkansas", loc: "AWAY", venue: "Fayetteville, Ark." },
    { week: 3, date: "SAT SEP 19", opponent: "Arizona State", loc: "AWAY", venue: "Tempe, Ariz." },
    { week: 4, date: "SAT SEP 26", opponent: "UCF", loc: "HOME", venue: "Stillwater, Okla." },
    { week: 5, date: "SAT OCT 3", opponent: "Baylor", loc: "HOME", venue: "Stillwater, Okla." },
    { week: 6, date: "SAT OCT 10", opponent: "Iowa State", loc: "AWAY", venue: "Ames, Iowa" },
    { week: 7, date: "SAT OCT 17", opponent: "Kansas", loc: "HOME", venue: "Stillwater, Okla." },
    { week: 8, date: "SAT OCT 31", opponent: "Colorado", loc: "HOME", venue: "Stillwater, Okla." },
    { week: 9, date: "SAT NOV 7", opponent: "West Virginia", loc: "AWAY", venue: "Morgantown, W.Va." },
    { week: 10, date: "SAT NOV 14", opponent: "Cincinnati", loc: "AWAY", venue: "Cincinnati, Ohio" },
    { week: 11, date: "SAT NOV 21", opponent: "Texas Tech", loc: "HOME", venue: "Stillwater, Okla." },
    { week: 12, date: "SAT NOV 28", opponent: "Oklahoma", loc: "AWAY", venue: "Norman, Okla." },
  ],
  TCU: [
    { week: 1, date: "SAT SEP 5", opponent: "Texas Southern", loc: "HOME", venue: "Fort Worth, Texas" },
    { week: 2, date: "SAT SEP 12", opponent: "SMU", loc: "HOME", venue: "Fort Worth, Texas" },
    { week: 3, date: "SAT SEP 19", opponent: "Houston Baptist", loc: "HOME", venue: "Fort Worth, Texas" },
    { week: 4, date: "SAT SEP 26", opponent: "Colorado", loc: "HOME", venue: "Fort Worth, Texas" },
    { week: 5, date: "SAT OCT 3", opponent: "Utah", loc: "AWAY", venue: "Salt Lake City, Utah" },
    { week: 6, date: "SAT OCT 10", opponent: "Kansas State", loc: "HOME", venue: "Fort Worth, Texas" },
    { week: 7, date: "SAT OCT 17", opponent: "West Virginia", loc: "AWAY", venue: "Morgantown, W.Va." },
    { week: 8, date: "SAT OCT 31", opponent: "Texas Tech", loc: "HOME", venue: "Fort Worth, Texas" },
    { week: 9, date: "SAT NOV 7", opponent: "Arizona State", loc: "HOME", venue: "Fort Worth, Texas" },
    { week: 10, date: "SAT NOV 14", opponent: "UCF", loc: "AWAY", venue: "Orlando, Fla." },
    { week: 11, date: "SAT NOV 21", opponent: "Oklahoma State", loc: "AWAY", venue: "Stillwater, Okla." },
    { week: 12, date: "SAT NOV 28", opponent: "Baylor", loc: "HOME", venue: "Fort Worth, Texas" },
  ],
  "Texas Tech": [
    { week: 1, date: "SAT SEP 5", opponent: "Abilene Christian", loc: "HOME", venue: "Lubbock, Texas" },
    { week: 2, date: "SAT SEP 12", opponent: "Tennessee", loc: "AWAY", venue: "Knoxville, Tenn." },
    { week: 3, date: "SAT SEP 19", opponent: "North Texas", loc: "HOME", venue: "Lubbock, Texas" },
    { week: 4, date: "SAT SEP 26", opponent: "UCF", loc: "AWAY", venue: "Orlando, Fla." },
    { week: 5, date: "SAT OCT 3", opponent: "Houston", loc: "AWAY", venue: "Houston, Texas" },
    { week: 6, date: "SAT OCT 10", opponent: "Utah", loc: "HOME", venue: "Lubbock, Texas" },
    { week: 7, date: "SAT OCT 17", opponent: "Colorado", loc: "AWAY", venue: "Boulder, Colo." },
    { week: 8, date: "SAT OCT 31", opponent: "TCU", loc: "AWAY", venue: "Fort Worth, Texas" },
    { week: 9, date: "SAT NOV 7", opponent: "Kansas", loc: "HOME", venue: "Lubbock, Texas" },
    { week: 10, date: "SAT NOV 14", opponent: "Baylor", loc: "HOME", venue: "Lubbock, Texas" },
    { week: 11, date: "SAT NOV 21", opponent: "Oklahoma State", loc: "AWAY", venue: "Stillwater, Okla." },
    { week: 12, date: "SAT NOV 28", opponent: "West Virginia", loc: "HOME", venue: "Lubbock, Texas" },
  ],
  UCF: [
    { week: 1, date: "SAT SEP 5", opponent: "Florida A&M", loc: "HOME", venue: "Orlando, Fla." },
    { week: 2, date: "SAT SEP 12", opponent: "South Florida", loc: "HOME", venue: "Orlando, Fla." },
    { week: 3, date: "SAT SEP 19", opponent: "FIU", loc: "HOME", venue: "Orlando, Fla." },
    { week: 4, date: "SAT SEP 26", opponent: "Oklahoma State", loc: "AWAY", venue: "Stillwater, Okla." },
    { week: 5, date: "SAT OCT 3", opponent: "Arizona", loc: "HOME", venue: "Orlando, Fla." },
    { week: 6, date: "SAT OCT 10", opponent: "Cincinnati", loc: "HOME", venue: "Orlando, Fla." },
    { week: 7, date: "SAT OCT 17", opponent: "Houston", loc: "AWAY", venue: "Houston, Texas" },
    { week: 8, date: "SAT OCT 31", opponent: "Kansas", loc: "AWAY", venue: "Lawrence, Kan." },
    { week: 9, date: "SAT NOV 7", opponent: "BYU", loc: "HOME", venue: "Orlando, Fla." },
    { week: 10, date: "SAT NOV 14", opponent: "Iowa State", loc: "AWAY", venue: "Ames, Iowa" },
    { week: 11, date: "SAT NOV 21", opponent: "TCU", loc: "HOME", venue: "Orlando, Fla." },
    { week: 12, date: "SAT NOV 28", opponent: "West Virginia", loc: "AWAY", venue: "Morgantown, W.Va." },
  ],
  Utah: [
    { week: 1, date: "SAT SEP 5", opponent: "Weber State", loc: "HOME", venue: "Salt Lake City, Utah" },
    { week: 2, date: "SAT SEP 12", opponent: "Baylor", loc: "HOME", venue: "Salt Lake City, Utah" },
    { week: 3, date: "SAT SEP 19", opponent: "Wyoming", loc: "HOME", venue: "Salt Lake City, Utah" },
    { week: 4, date: "SAT SEP 26", opponent: "Arizona State", loc: "HOME", venue: "Salt Lake City, Utah" },
    { week: 5, date: "SAT OCT 3", opponent: "TCU", loc: "HOME", venue: "Salt Lake City, Utah" },
    { week: 6, date: "SAT OCT 10", opponent: "Texas Tech", loc: "AWAY", venue: "Lubbock, Texas" },
    { week: 7, date: "SAT OCT 17", opponent: "Iowa State", loc: "HOME", venue: "Salt Lake City, Utah" },
    { week: 8, date: "SAT OCT 31", opponent: "West Virginia", loc: "AWAY", venue: "Morgantown, W.Va." },
    { week: 9, date: "SAT NOV 7", opponent: "Kansas State", loc: "AWAY", venue: "Manhattan, Kan." },
    { week: 10, date: "SAT NOV 14", opponent: "Arizona", loc: "HOME", venue: "Salt Lake City, Utah" },
    { week: 11, date: "SAT NOV 21", opponent: "Colorado", loc: "AWAY", venue: "Boulder, Colo." },
    { week: 12, date: "SAT NOV 28", opponent: "BYU", loc: "AWAY", venue: "Provo, Utah" },
  ],
  "West Virginia": [
    { week: 1, date: "SAT SEP 5", opponent: "Eastern Kentucky", loc: "HOME", venue: "Morgantown, W.Va." },
    { week: 2, date: "SAT SEP 12", opponent: "Virginia Tech", loc: "HOME", venue: "Morgantown, W.Va." },
    { week: 3, date: "SAT SEP 19", opponent: "Penn State", loc: "AWAY", venue: "University Park, Pa." },
    { week: 4, date: "SAT SEP 26", opponent: "Baylor", loc: "AWAY", venue: "Waco, Texas" },
    { week: 5, date: "SAT OCT 3", opponent: "Kansas State", loc: "AWAY", venue: "Manhattan, Kan." },
    { week: 6, date: "SAT OCT 10", opponent: "BYU", loc: "HOME", venue: "Morgantown, W.Va." },
    { week: 7, date: "SAT OCT 17", opponent: "TCU", loc: "HOME", venue: "Morgantown, W.Va." },
    { week: 8, date: "SAT OCT 31", opponent: "Utah", loc: "HOME", venue: "Morgantown, W.Va." },
    { week: 9, date: "SAT NOV 7", opponent: "Oklahoma State", loc: "HOME", venue: "Morgantown, W.Va." },
    { week: 10, date: "SAT NOV 14", opponent: "Houston", loc: "HOME", venue: "Morgantown, W.Va." },
    { week: 11, date: "SAT NOV 21", opponent: "Cincinnati", loc: "AWAY", venue: "Cincinnati, Ohio" },
    { week: 12, date: "SAT NOV 28", opponent: "Texas Tech", loc: "AWAY", venue: "Lubbock, Texas" },
  ],
};

/* ------------------------------------------------------------------ */
/*  Public helpers                                                     */
/* ------------------------------------------------------------------ */

export function getTeamSchedule(team: string): Game[] {
  return SCHEDULES[team] || [];
}

export function isConferenceGame(opponent: string, team: string): boolean {
  const teamConf = ALL_TEAMS[team];
  if (!teamConf) return false;
  return ALL_TEAMS[opponent] === teamConf;
}

/* ------------------------------------------------------------------ */
/*  Spread math (unchanged)                                            */
/* ------------------------------------------------------------------ */

function winPctToFairSpread(winPct: number): number {
  if (winPct <= 0 || winPct >= 100) return winPct <= 0 ? 50 : -50;
  const p = winPct / 100;
  const logit = Math.log(p / (1 - p));
  return -logit * 8.0;
}

export function getImpliedSpread(winPct: number, isHome: boolean): number | null {
  if (isNaN(winPct) || winPct < 0 || winPct > 100) return null;
  const neutralSpread = winPctToFairSpread(winPct);
  const HFA = 2.75;
  return isHome ? neutralSpread - HFA : neutralSpread + HFA;
}

export function formatSpread(spread: number | null): string {
  if (spread === null) return "—";
  const abs = Math.abs(spread);
  if (abs < 0.5) return "Pick'em";
  const rounded = Math.round(abs * 2) / 2;
  if (spread < 0) return `NEB -${rounded.toFixed(1)}`;
  return `OPP -${rounded.toFixed(1)}`;
}

export type SpreadSentiment = "positive" | "negative" | "neutral" | "none";

export function getSpreadSentiment(spread: number | null): SpreadSentiment {
  if (spread === null) return "none";
  if (Math.abs(spread) < 0.5) return "neutral";
  if (spread < 0) return "positive";
  return "negative";
}
