// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/list-teams.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
import { ALL_TEAMS, CONFERENCES } from "npm:@/lib/oddsmaker";
var list_teams_default = defineTool({
  name: "list_teams",
  title: "List P4 teams",
  description: "List the 67 Power 4 (ACC, Big 12, Big Ten, SEC) college football teams covered by this app, optionally filtered by conference.",
  inputSchema: {
    conference: z.enum(["ACC", "Big 12", "Big Ten", "SEC"]).optional().describe("Optional conference filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ conference }) => {
    const teams = conference ? CONFERENCES[conference] ?? [] : Object.keys(ALL_TEAMS).sort();
    const rows = teams.map((team) => ({
      team,
      conference: ALL_TEAMS[team]?.conference ?? ""
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, teams: rows }
    };
  }
});

// src/lib/mcp/tools/get-schedule.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z2 } from "npm:zod@^4.4.3";
import { ALL_TEAMS as ALL_TEAMS2 } from "npm:@/lib/oddsmaker";
var get_schedule_default = defineTool2({
  name: "get_schedule",
  title: "Get 2026 schedule",
  description: "Return the 2026 regular-season schedule for a Power 4 team: week, date, opponent, and home/away/neutral location.",
  inputSchema: {
    team: z2.string().min(1).describe('Team name exactly as returned by list_teams, e.g. "Nebraska".')
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ team }) => {
    const info = ALL_TEAMS2[team];
    if (!info) {
      return {
        content: [
          {
            type: "text",
            text: `Unknown team "${team}". Call list_teams for valid names.`
          }
        ],
        isError: true
      };
    }
    const games = info.schedule.map((g) => ({
      week: g.week,
      date: g.date,
      opponent: g.opponent,
      location: g.loc,
      venue: g.venue
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(games, null, 2) }],
      structuredContent: { team, conference: info.conference, games }
    };
  }
});

// src/lib/mcp/tools/project-season-wins.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z3 } from "npm:zod@^4.4.3";
import { ALL_TEAMS as ALL_TEAMS3, computeDistribution, isConferenceGame } from "npm:@/lib/oddsmaker";
var project_season_wins_default = defineTool3({
  name: "project_season_wins",
  title: "Project season wins",
  description: "Given per-game win percentages (0-100) for a team's 12 regular-season games, return expected wins, the full 0-12 win distribution (dynamic programming over Bernoulli trials), and conference win totals.",
  inputSchema: {
    team: z3.string().min(1).describe("Team name (see list_teams)."),
    win_percentages: z3.array(z3.number().min(0).max(100)).describe(
      "Win percentage per game in schedule order (see get_schedule). Length must match the team's schedule (typically 12)."
    )
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ team, win_percentages }) => {
    const info = ALL_TEAMS3[team];
    if (!info) {
      return {
        content: [{ type: "text", text: `Unknown team "${team}".` }],
        isError: true
      };
    }
    const games = info.schedule;
    if (win_percentages.length !== games.length) {
      return {
        content: [
          {
            type: "text",
            text: `Expected ${games.length} win percentages for ${team}, got ${win_percentages.length}.`
          }
        ],
        isError: true
      };
    }
    const probs = win_percentages.map((p) => p / 100);
    const dist = computeDistribution(probs);
    const expected = probs.reduce((a, b) => a + b, 0);
    const confProbs = probs.filter((_, i) => isConferenceGame(games[i].opponent, team));
    const confExpected = confProbs.reduce((a, b) => a + b, 0);
    const distribution = dist.map((prob, wins) => ({
      wins,
      probability: Number(prob.toFixed(6))
    }));
    const bowlEligible = dist.slice(6).reduce((a, b) => a + b, 0);
    return {
      content: [
        {
          type: "text",
          text: `Expected wins: ${expected.toFixed(2)} (conference: ${confExpected.toFixed(2)}). Bowl-eligible (\u22656 wins): ${(bowlEligible * 100).toFixed(1)}%.`
        }
      ],
      structuredContent: {
        team,
        expected_wins: Number(expected.toFixed(4)),
        expected_conference_wins: Number(confExpected.toFixed(4)),
        bowl_eligible_probability: Number(bowlEligible.toFixed(4)),
        win_distribution: distribution
      }
    };
  }
});

// src/lib/mcp/tools/get-program-analytics.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z as z4 } from "npm:zod@^4.4.3";
import { ANALYTICS_DATA } from "npm:@/lib/analyticsData";
var get_program_analytics_default = defineTool4({
  name: "get_program_analytics",
  title: "Get program analytics",
  description: "Return 2016-2025 program analytics for a Power 4 team: SP+ ranks, 247Sports recruiting composite ranks, and the Delta (recruiting minus performance) metric with average and standard deviation.",
  inputSchema: {
    team: z4.string().min(1).describe("Team name (see list_teams).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ team }) => {
    const row = ANALYTICS_DATA.find(
      (t) => t.team.toLowerCase() === team.toLowerCase()
    );
    if (!row) {
      return {
        content: [
          {
            type: "text",
            text: `No analytics found for "${team}". Call list_teams for valid names.`
          }
        ],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(row, null, 2) }],
      structuredContent: row
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "p4-oddsmaker-mcp",
  title: "P4 Oddsmaker (2026)",
  version: "0.1.0",
  instructions: "Public read-only tools for the 2026 Power 4 college football season projection app. Use list_teams to discover team names, get_schedule for a team's 2026 schedule, project_season_wins to compute the win distribution given per-game win percentages, and get_program_analytics for 2016-2025 SP+/247Sports/Delta metrics. All data is public and this server is not affiliated with the University of Nebraska.",
  tools: [list_teams_default, get_schedule_default, project_season_wins_default, get_program_analytics_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
